### PR TITLE
PP-383: Add smoke tags to all smoke test cases in pbs_smoketest.py

### PR DESCRIPTION
**Pull request by saritakh**
#### Issue-ID

* **[PP-383](https://pbspro.atlassian.net/browse/PP-383)**

#### Problem description
* All smoke test cases in pbs_smoketest.py should be tagged with "smoke" tag

#### Cause / Analysis
* Smoke test cases need to be tagged

#### Solution description
* Apply "smoke" tag to test suite in pbs_smoketest.py

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by agrawalravi90** [comment]
@saritakh , this pull request failed CI (not sure if you get notified when this happens), please investigate.

**Comment by subhasisb** [comment]
Travis is experiencing technical hiccups. Waiting for it to settle down.

**Comment by agrawalravi90** [comment]
This looks good to me, I sign-off.
One comment though: Please attach evidence of testing/test logs to the ticket. I had to pull this locally and run "pbs_benchpress --tags=smoke" to verify, the logs would have helped. Thanks!

**Comment by saritakh** [comment]
@agrawalravi90
Thanks, comment noted. I have attached the test logs to ticket PP-383.

**Comment by hirenvadalia** [comment]
Changes looks good. I sign-off.

**Comment by subhasisb** [comment]
All looks good. Merging now.

**Comment by subhasisb** [comment]
And I sign off too.

**Pull request merged**
