### PR TITLE
PP-301 :Scheduler does not import python math module

### PR DESCRIPTION
**Pull request by chitrac**
#### Issue-ID

* PP-301

#### Problem description
Scheduler does not import python math module

#### Cause / Analysis
An extra colon before the import of math module 

#### Solution description
*Removing the extra colon imports the math module correctly

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [x] I have added tests to cover my changes. To create automated tests, see **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**.
- [x] All new and existing automated tests have passed. See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**.
- [x] I have attached automated (PTL)/manual test logs to the associated Jira ticket.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

Scheduler does not import python math module

### CODE REVIEW

**Comment by bremanandjk** [comment]
@chitrac,

Thanks for your changes, Please share your PTL/manual test results too.

**Comment by chitrac** [comment]
Logs Before the fix :
06/30/2016 14:11:49;0080;pbs_sched;Req;;Leaving Scheduling Cycle
06/30/2016 14:21:50;0080;pbs_sched;Req;;Starting Scheduling Cycle
06/30/2016 14:21:50;0040;pbs_sched;Node;;Error getting nodes: Server has no node list
06/30/2016 14:21:50;0002;pbs_sched;Svr;;Problem with creating server data structure
06/30/2016 14:21:50;0080;pbs_sched;Req;;Leaving Scheduling Cycle
06/30/2016 14:31:49;0080;pbs_sched;Req;;Starting Scheduling Cycle
06/30/2016 14:31:49;0040;pbs_sched;Node;;Error getting nodes: Server has no node list
06/30/2016 14:31:49;0002;pbs_sched;Svr;;Problem with creating server data structure
06/30/2016 14:31:49;0080;pbs_sched;Req;;Leaving Scheduling Cycle
06/30/2016 14:41:49;0080;pbs_sched;Req;;Starting Scheduling Cycle
06/30/2016 14:41:49;0040;pbs_sched;Node;;Error getting nodes: Server has no node list
06/30/2016 14:41:49;0002;pbs_sched;Svr;;Problem with creating server data structure
06/30/2016 14:41:49;0080;pbs_sched;Req;;Leaving Scheduling Cycle
06/30/2016 14:51:49;0080;pbs_sched;Req;;Starting Scheduling Cycle
06/30/2016 14:51:49;0040;pbs_sched;Node;;Error getting nodes: Server has no node list
06/30/2016 14:51:49;0002;pbs_sched;Svr;;Problem with creating server data structure
06/30/2016 14:51:49;0080;pbs_sched;Req;;Leaving Scheduling Cycle
06/30/2016 14:53:29;0002;pbs_sched;Svr;die;caught signal 15
06/30/2016 14:53:29;0002;pbs_sched;Svr;Log;Log closed
06/30/2016 14:53:31;0002;pbs_sched;Svr;Log;Log opened
06/30/2016 14:53:31;0002;pbs_sched;Svr;pbs_sched;pbs_version=13.1.800
06/30/2016 14:53:31;0002;pbs_sched;Svr;pbs_sched;pbs_build=mach=N/A:security=N/A:configure_args=N/A
06/30/2016 14:53:31;0002;pbs_sched;n/a;setup_env;read environment from /var/spool/pbs/pbs_environment
06/30/2016 14:53:31;0040;pbs_sched;Fil;sched_config;Obsolete config name sort_queues
06/30/2016 14:53:31;0040;pbs_sched;Sched;PythonError; No module named math. Python is unlikely to work properly.
06/30/2016 14:53:31;0006;pbs_sched;Fil;pbs_sched;Version 13.1.800, started, initialization type = 0
06/30/2016 14:53:31;0002;pbs_sched;Svr;main;/opt/pbs/sbin/pbs_sched startup pid 21224
06/30/2016 14:53:31;0d80;pbs_sched;TPP;pbs_sched(Main Thread);TPP set to use reserved port authentication
06/30/2016 14:53:31;0d80;pbs_sched;TPP;pbs_sched(Main Thread);Initializing TPP transport Layer
Scenario After The Fix:
Added opt_backfill_fuzzy_time: 600 in sched config
Restart PBS.
And then checked the logs : for any import error for math module which was not found after the fix.

**Comment by subhasisb** [comment]
@chitrac please add all the logs to the Jira ticket

**Comment by chitrac** [comment]
@subhasisb - Thank you for the comment , I have added the logs in the JIRA ticket PBS-14667.

**Comment by arungrover** [comment]
Change looks good. I sign-off

**Comment by nithinj** [comment]
Changes looks good to me. I sign-off

**Comment by chitrac** [comment]
@arungrover and @nithinj Thank you for the sign-off.
Hello @subhasisb - I have attached the logs with the Jira ticket and also mentioned the same in the comment section here and in JIRA ticket.
Thank You.

**Pull request merged**
