### PR TITLE
PP-977: pbs_admin_suspend.py test_offline needs to be updated to not …

### PR DESCRIPTION
**Pull request by anamikau**
…reuse job object

#### Issue-ID

* **[PP-977](https://pbspro.atlassian.net/browse/PP-977)**

#### Problem description
* Due to same job object job submission was failing

#### Cause / Analysis
* job submissions are failing as same job object was used for submitting multiple jobs

#### Solution description
* added new job object instead of reusing the job object

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
Thanks for fixing this.  I sign off.  Please rebase for the merge.

**Comment by anamikau** [comment]
Thanks @arungrover and @bhroam . I have rebased my branch. Please take it forward.

**Comment by anamikau** [comment]
@arungrover and @bhroam , I found a typo in the file I changed. Please do not merge this request.
I will be updating the file further.

**Comment by anamikau** [comment]
@arungrover and @bhroam , please review it again.

**Comment by arungrover** [comment]
Change looks good. 
Can you please attach test logs of this change to the ticket.

**Comment by anamikau** [comment]
@arungrover , done.

**Comment by bhroam** [comment]
Looks good to me.  I sign off.  Please squash and rebase.

**Comment by anamikau** [comment]
@bhroam , squashed and rebased, please take it further

**Comment by bhroam** [comment]
Something was merged ahead of us.  Please rebase again.

**Comment by anamikau** [comment]
@bhroam , rebased again. please take it forward.

**Comment by bhroam** [comment]
merged

**Pull request merged**
