### PR TITLE
PP-858: Revert "PP-803: Run tests from newly added or modified test file along with smoke tests in Travis"

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Issue-ID

* **[PP-858](https://pbspro.atlassian.net/browse/PP-858)**

#### Problem description
*  [PP-803](https://pbspro.atlassian.net/browse/PP-803) was thought to be a good idea to run the tests being checked into a PR with Travis, but there are some technical challenges and limitation by Travis, which make it seem infeasible for now:
     * Travis has a timeout of 50 minutes and if a job exceeds that, it blocks the corresponding PR. So, if a PR contains many newly added tests then it can cause Travis to timeout.
     * There are rooms for adding more smoke tests which might be more valuable to run on a new code change than running new test cases being checked in, under Travis time limits.

#### Cause / Analysis
* Technical challenges and limitation on Travis

#### Solution description
* Revert changes done by PP-803

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by arungrover** [comment]
@hirenvadalia please rebase the branch for merge

**Comment by hirenvadalia** [comment]
@arungrover I have re-based branch with master, please take it further once Travis completes... Thanks

**Comment by arungrover** [comment]
@hirenvadalia it's again out of date. Please rebase it again.

**Comment by hirenvadalia** [comment]
@arungrover done, re-based again

**Comment by arungrover** [comment]
merged

**Comment by hirenvadalia** [comment]
Thanks @arungrover

**Pull request merged**
