### PR TITLE
(commit 2) fixes to job array wrt -o,-e,-R and direct write qsub options

### PR DESCRIPTION
**Pull request by Shrini-h**
#### Bug/feature Description

Additions to merged PR https://github.com/PBSPro/pbspro/pull/892  commit https://github.com/PBSPro/pbspro/commit/4ae25fdb425a11196e7e3d0ed40cfd74d0728473
To handle windows case and use snprintf instead of strncpy

* *There were issues related to sub job std outputs when used with -o/-e/-R/direct write (-koed) options for Job Array*
* *-R was not working for job array subjobs*
* *-o/-e the std files of all subjobs got overwritten to same file (regression from https://github.com/PBSPro/pbspro/pull/358 )*
* *direct write (-koed) was also making subjobs to overwrite std files to same file*

#### Affected Platform(s)
* *All*

#### Cause / Analysis / Design
* *Cause was due to flawed handling of JOB_ATR_outpath and JOB_ATR_errpath job attributes in server and mom*

#### Solution Description
* *Correct handling of JOB_ATR_outpath and JOB_ATR_errpath job attributes in server and mom*

#### Testing logs/output
[Test_report_logs.zip](https://github.com/PBSPro/pbspro/files/2638319/Test_report_logs.zip)

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [x] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by Shrini-h** [comment]
Tagging, @nithinj  @arungrover  @subhasisb

**Comment by arungrover** [comment]
Please change the commit title to reflect the problem you are fixing in this second commit

**Comment by Shrini-h** [comment]
I have changed the commit title, while squashing and rebasing.  I have kept the PR title as it is.
PR ready for merge

**Comment by Shrini-h** [comment]
@subhasisb / @arungrover , Please take over for merging
Thank You

**Pull request merged**
