### PR TITLE
PP-835: Travis failing due to new updated Trusty images

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Issue-ID

* **[PP-835](https://pbspro.atlassian.net/browse/PP-835)**

#### Problem description
* Travis might fail

#### Cause / Analysis
* Newly updated Trusty images (https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch)

#### Solution description
* Added workaround suggested by above link.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by hirenvadalia** [comment]
Since this is fix for Travis-CI no new PTL test or not manual test required.

**Comment by arungrover** [comment]
looks good @hirenvadalia

**Comment by arungrover** [comment]
merged

**Comment by hirenvadalia** [comment]
Thanks @arungrover and @kjakkali for promote reviews and actions.

**Pull request merged**
