### PR TITLE
PP-994: fix link to docker multi-stage build documentation

### PR DESCRIPTION
**Pull request by minghui-liu**
#### Issue-ID

* **[PP-994](https://pbspro.atlassian.net/browse/PP-994)**

#### Problem description
The link to docker multi-stage build documentation is wrong.

#### Solution description
Fixed link url.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by minghui-liu** [comment]
@PBSPro/pbspro-maintainers I have rebased my branch. Please take it further. Thanks.

**Comment by mike0042** [comment]
Looks like another PR made it in. Please rebase once again.

**Comment by minghui-liu** [comment]
@mike0042 Done.

**Comment by bhroam** [comment]
Looks good to me.  I sign off.  Please rebase for the final merge.

**Comment by minghui-liu** [comment]
@bhroam Rebased.

**Comment by bhroam** [comment]
Thanks for rebasing again @minghui-liu.  Sorry for having to do it so many times.  I merged in the PR.

**Comment by minghui-liu** [comment]
No a problem. Thank you @bhroam and @mike0042 .

**Pull request merged**
