### PR TITLE
Updates pbs_holidays file for 2018 (replaces 2016 holidays file)

### PR DESCRIPTION
**Pull request by dw808303**
#### Bug/feature Description
* The current pbs_holidays file dates to 2016. Using the 2016 holidays file as of this date (2018-Oct-03) results in a warning message in the scheduler logs, once per scheduling cycle.
* *To reproduce, simply start pbs with the `pbs_holidays` file from the current source tree in place in `$PBS_HOME/sched_priv/holidays`

#### Affected Platform(s)
* *Platform: All (observed on CentOS 7.3)*

#### Cause / Analysis / Design
* *Holidays file, as shipped, is two years out of date*

#### Solution Description
* *Replaces 2016 holidays with 2018 holidays*
* *Will create a 2019 holidays file if this pull is accepted*

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by mike0042** [comment]
@PBSPro/pbspro-maintainers : Normally, we require test logs to accompany all pull requests. However, this is simply an update to the holiday file. I propose we merge this as is. Any objections?

**Comment by agrawalravi90** [comment]
That sounds good Mike. @dw808303 , sorry for the delay, please rebase your branch so that it can get merged. Thanks for your contribution!

**Comment by dw808303** [comment]
> That sounds good Mike. @dw808303 , sorry for the delay, please rebase your branch so that it can get merged. Thanks for your contribution!

Sorry, just saw this.  Did I do it right?

**Comment by agrawalravi90** [comment]
your branch is still out of date, are you sure you did a git push -f ? After a rebase, you need to use the -f flag.

**Comment by mike0042** [comment]
Hi Dave,

I see you did not create a separate branch for your changes and applied them to your local master branch. That's OK, but not generally how we recommend developers author changes. Here's the steps I recommend you follow to rebase:
1. cd to your dev branch
2. Run 'git status' to make sure you're on the branch you want to be (master in this case)
3. Run 'git fetch --all --prune' to sync you local branch with the remote
4. Run 'git rebase upstream/master' to pull in the changes from remote
5. Run 'git commit --amend --no-edit -S' to resign your commit
6. Run 'git push -f origin master' to forcibly update your remote branch

At that point the Travis and Appveyor builds will run. Once complete, your pull request will be ready for one of the maintainers to merge.

**Comment by mike0042** [comment]
Merged. Thanks @dw808303!

**Pull request merged**
