### PR TITLE
PP-575: pbs_test_qorder.py script is not present in the correct direc…

### PR DESCRIPTION
**Pull request by arungrover**
#### Issue-ID

* **[PP-575](https://pbspro.atlassian.net/browse/PP-575)**

#### Problem description
pbs_test_qorder.py was wrongly placed in "...test/tests"

#### Cause / Analysis
wrong file placement

#### Solution description
moved to functional directory

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

…tory

### CODE REVIEW

**Comment by arungrover** [comment]
@PBSPro/pbspro-maintainers  @vinodchitrali there are some problems with travis.
On OpenSUSE 13.2 "docker exec -it testdev /bin/sh -c 'cp -fv pbspro-*.tar.gz /root/rpmbuild/SOURCES/'" reports a wrong exit status.
It seems that it is happening only when docker exec is used with '-t' option where it created a pseudo tty is created.
Another problem is that now scripts are using "-xe" option, it exits on this error and then travis retries to run the same script which causes it to fail right on the first statement of the script because the packages that the script is trying to install are already installed.

**Comment by rampranesh** [comment]
Changes looks good!

**Comment by bhroam** [comment]
Looks good.  I sign off.

**Comment by bhroam** [comment]
merged

**Pull request merged**
