### PR TITLE
PP-423: Travis should check for PEP8 compliancy of Python code changes

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Issue-ID

* **[PP-423](https://pbspro.atlassian.net/browse/PP-423)**

#### Problem description
* Add PEP8 compliance check for PTL

#### Cause / Analysis
* None

#### Solution description
* Added check for PEP8 compliance for PTL
* It will mark build as failed if any code in PTL is not PEP8 compliance
* Also applied PEP8 style on existing PTL test cases

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by kjakkali** [comment]
Changes looks good. I sign off.

**Comment by subhasisb** [comment]
Changes look good. I sign off.

**Comment by subhasisb** [comment]
@Hiren please add the Travis test log to the Jira ticket as evidence of testing

**Comment by subhasisb** [comment]
All good. Merging.

**Comment by hirenvadalia** [comment]
@subhasisb I have updated ticket with logs.

**Pull request merged**
