### PR TITLE
PP-1032-1127: preempted jobs aren't put in their own equivalence clas…

### PR DESCRIPTION
**Pull request by prakashcv13**
…ses.

#### Issue-ID

* **[PP-1032](https://pbspro.atlassian.net/browse/PP-1032)**
* **[PP-1127](https://pbspro.atlassian.net/browse/PP-1127)**

#### Problem description
* The fix for PP-863 was broken.
* preempted jobs aren't put in their own equivalence classes.

#### Cause / Analysis
* While rebasing and squashing PR-346, with the then latest master, it looks like the execselect defined under job_info structure got re-introduced.

#### Solution description
* Removed the execselect from the job_info structure.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
Looks good, I sign off.

**Comment by prakashcv13** [comment]
Hi @bhroam, I have rebased my branch, request you to merge this PR.

**Comment by hirenvadalia** [comment]
@prakashcv13 I think you need to update commit message and PR title with proper ticket ids... like ```PP-XXX, PP-YYY``` instead PP-XXX-YYY.

**Comment by prakashcv13** [comment]
@hirenvadalia, I used the similar format in [PR# 455](https://github.com/PBSPro/pbspro/pull/455), would like to use the same here.

**Comment by bhroam** [comment]
I merged in the PR.

**Comment by prakashcv13** [comment]
thank you @bhroam.

**Pull request merged**
