### PR TITLE
PP-451: Fix commands/server communication delays caused by Nagle's

### PR DESCRIPTION
**Pull request by subhasisb**
#### Issue-ID

* **[PP-451](https://pbspro.atlassian.net/browse/PP-451)**

#### Problem description
* commands/server communication due to Nagle's when replies from server are larger than 1024 bytes

#### Cause / Analysis
* When the TCP buffer sizes are just a little larger than 1024 bytes, Nagle's algorithm slows down the communication between the server and the commands

#### Solution description
* Disable Nagle's algorithm on both sides of the connection from clients/server.

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [X] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [X] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [X] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by subhasisb** [comment]
Travis test results attached to Jira ticket
PTL test case is part of commit
PTL test results before and after fix is attached to Jira ticket

**Comment by mike0042** [comment]
I sign off on this change.

**Comment by agrawalravi90** [comment]
@subhasisb Carl had raised a concern on the removal of Nagle's Algorithm (please see his comment on the ticket), could you please address his comment? Thanks!

**Comment by subhasisb** [comment]
@agrawalravi90 I have responded to him. We will wait to see what he thinks.

**Comment by agrawalravi90** [comment]
@subhasisb Quick question: can this negatively impact the time taken by server to connect to all moms when the server is restarted on a system with large number of moms? I'm guessing this event is rare enough that we don't care but I wanted to bring it up just in case.

**Comment by subhasisb** [comment]
@agrawalravi90 Thanks for the question. No this will not affect server's communication with mom, since server does not have direct TCP connections to mom, rather they talk over TPP (pbs_comm). Those connections follow a different code path and does not use net_server.c/net_client.c.

**Comment by agrawalravi90** [comment]
Alright, this looks good enough to me, and I had a discussion with Carl and I think he mostly thinks that this is safe as well, so I'm going to merge it in.

**Comment by agrawalravi90** [comment]
Actually, could you please bring your branch up to date with master? It'll be faster than me creating a separate merge commit. Thanks!

**Comment by prakashcv13** [comment]
@subhasisb, not sure if PP-367 wherebywe send only small files over TPP otherwise we fork, would be affected or vice versa.

**Comment by subhasisb** [comment]
@prakash , the case of PP-367 should be few and yes the forked TCP send_job processes will be get the nagles algorithm enabled. However, the internal network within a cluster is usually fast. Also the amount of data we are sending in those IFL requests are not small single character packets, rather fairly large file chunks. So, overall, there will not be any impact. Thanks for asking.

**Comment by agrawalravi90** [comment]
@prakashcv13 do you have any further comments?

**Comment by prakashcv13** [comment]
@subhasisb, thank you for the confirmation.

**Comment by agrawalravi90** [comment]
Alright, merging this in

**Pull request merged**
