### PR TITLE
PP-721: Error observed when post analysis data is saved in PTL test execution that has failed tests

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Issue-ID

* **[PP-721](https://pbspro.atlassian.net/browse/PP-721)**

#### Problem description
* -u argument is missing while calling pbs_diag in saving post analysis data

#### Cause / Analysis
* -u argument is required to collect pbs_dtj information if you have jobs in systems, without -u argument pbs_diag will skip collecting pbs_dtj information for specified jobs

#### Solution description
* added -u while calling pbs_diag in post data saving

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by saritakh** [comment]
Change looks good to me.

**Comment by arungrover** [comment]
@hirenvadalia Change looks good.
Although, the test logs are just CI logs. The bug is about a test case failure resulting into error while saving post analysis data. I do not see that getting tested in logs attached to the ticket.

**Comment by saritakh** [comment]
@arungrover I have attached the PTL test logs of saving post analysis data for a test failure, before this fix and after this fix; to the JIRA ticket PP-721.
We need to run a failed test with log level DEBUG2 in order to see the error returned by pbs_diag.

**Comment by bhroam** [comment]
What is the status of this PR?  It looks like it was almost finished.  Has the additional testing been done to finish it off?

**Comment by hirenvadalia** [comment]
@arungrover I have rebased branch with current master and @saritakh has added pre and post fix test results to ticket (Thanks @saritakh). Please have a look and let me know if anything is missing.

**Comment by arungrover** [comment]
Change looks good @hirenvadalia 
Please rebase again.

**Comment by hirenvadalia** [comment]
@arungrover Done, re-based with current master.

**Comment by arungrover** [comment]
merged

**Pull request merged**
