### PR TITLE
PP-293: Add check for signed commit in TravisCI

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Issue
* PP-293

#### Problem
* Add check for signed commit in TravisCI

#### Cause
* None

#### Solution
* Added scripts which will checks in TravisCI for whether all commits in pull request is signed or not... If any of the commits are not signed then it will stop TravisCI test and mark that CI request as failed. If all commits are signed then continue CI.

### CODE REVIEW

**Comment by subhasisb** [comment]
Looks good. I sign off. @hirenvadalia, please add/attach a test report to the Jira ticket showing that the updated Travis yml is working and able to catch an unsigned commit

**Comment by hirenvadalia** [comment]
Test results with unsigned commit:

For test commit: https://github.com/hirenvadalia/pbspro/pull/6/commits/aa30c5bda126c5c21af17560262288896fcee85e

$ .github/runchecks
Running check: 'checksign' ... FAILED
unsigned commits found in this pull request!
The command ".github/runchecks" failed and exited with 1 during .
Your build has been stopped.

**Comment by hirenvadalia** [comment]
@subhasisb Thanks for review I have added test results to JIRA as well as here for unsigned commits.

**Comment by kjakkali** [comment]
Change looks good. I sign off.

**Pull request merged**
