### PR TITLE
PP-648: sgigenvnodelist.awk fails on SLES 12 and RHEL 7

### PR DESCRIPTION
**Pull request by mike0042**
#### Issue-ID

* **[PP-648](https://pbspro.atlassian.net/browse/PP-648)**

#### Problem description
* sgigenvnodelist.awk fails on SLES 12 and RHEL 7

#### Cause / Analysis
* On SGI systems running older OSs the cpuset filesystem was mounted with the noprefix flag. New OSs mount the cpuset filesystem without noprefix which results in renaming of /dev/cpuset/cpus to /dev/cpuset/cpuset.cpus and /dev/cpuset/mems to /dev/cpuset/cpuset.mems.

#### Solution description
*  The script has been updated to take the new names into account while preserving backward compatibility.

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [X] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [X] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [X] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
Won't this still have the RHEL 6 issue?  I still see the -print in there.

**Comment by mike0042** [comment]
@bhroam you are absolutely correct. Thanks for catching that. The script has been updated.

**Comment by mike0042** [comment]
@bayucan please review the latest update.

**Comment by bhroam** [comment]
Looks good to me.  Go ahead and squash/rebase and I'll merge in your fix.

**Comment by mike0042** [comment]
@bhroam Squashed and rebased. Ready for merge.

**Comment by arungrover** [comment]
All looks good! 
merged

**Pull request merged**
