### PR TITLE
PP-649: qdel not working with seq_num.server

### PR DESCRIPTION
**Pull request by riyazhakki**
#### Issue-ID

* **[PP-649](https://pbspro.atlassian.net/browse/PP-649)**

#### Problem description
* qdel is not working with server tagged in the job id.

#### Cause / Analysis
* qdel is always speaking to PBS_SERVER defined in the /etc/pbs.conf file instead of the server tagged in the job id as get_server() function was not returning the server name parsed from the job id.

#### Solution description
* get_server() function is returning server_name parsed from the job id.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [x] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by arungrover** [comment]
Riyaz your change looks good. 
I have a minor comment about the ptl test case though. Please rename your test suite to something like"Test<functionality>" which follows our naming convention mentioned [here](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide#PTLQuickStartGuide-Addingtestcases).
Also, in you test case you expect the qdel command to fail but you never catch it. Well, technically there is no problem there but such a test script shows up as an "error" instead of "failure" when run. If you catch it's return code and test it against the error number like PBSE_BADHOST or something and then fail the test case then it will show up as failure.
We ideally should be looking for finding a failure in functionality rather than an "error" in the test case. What do you think?

**Comment by riyazhakki** [comment]
Hi Arun,
You are right! the test should show as failed instead of the error, That was the initial conduct of my code later in incremental code change I overlooked this.  I have addressed your comments please have a look.

**Comment by arungrover** [comment]
@riyazhakki your change looks good. Please rebase with latest changes for it to be merged

**Comment by arungrover** [comment]
All looks good, merging it now.

**Pull request merged**
