### PR TITLE
PP-60: Using kill -HUP `pgrep pbs_mom` could result in signal being sent to children of main MOM

### PR DESCRIPTION
**Pull request by sid2364**
#### Issue-ID

* **[PP-60](https://pbspro.atlassian.net/browse/PP-60)**

#### Problem description
* Jobs already running were going into 'E' state or being killed when pbs_mom is signalled HUP

#### Cause / Analysis
* Signal is not being handled properly

#### Solution description
* Added a proper signal handler.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by arungrover** [comment]
@sid2364 change looks good, any specific reason why no PTL test script is written

**Comment by sid2364** [comment]
@arungrover Will add the PTL test case. Initially I didn't write the test case since I thought there wasn't much value for automating this scenario, but after giving it some thought, it might actually be useful.

**Comment by arungrover** [comment]
Looks good @sid2364, please squash and rebase

**Comment by sid2364** [comment]
Have rebased and squashed the commits, @arungrover.

**Pull request merged**
