### PR TITLE
PP-671: logging via syslog does not work

### PR DESCRIPTION
**Pull request by mike0042**
#### Issue-ID

* **[PP-671](https://pbspro.atlassian.net/browse/PP-671)**

#### Problem description
* Logging to syslog no longer works

#### Cause / Analysis
* During the open source transition, the SYSLOG macro was mistakenly removed

#### Solution description
* Add the SYSLOG macro back into PBS Pro

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [X] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [X] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [X] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by arungrover** [comment]
Change looks good Mike!

**Comment by bhroam** [comment]
Please rebase for final merge.  It should kick travis which should work now.

**Comment by mike0042** [comment]
Travis is still broken. I'll rebase once things are working again.

**Comment by arungrover** [comment]
Merged.

**Pull request merged**
