### PR TITLE
PP-380: Update .gitignore to ignore files auto-generated by gtags and PBSTestLab

### PR DESCRIPTION
**Pull request by dilip-krishnan**
#### Issue-ID

* **[PP-380](https://pbspro.atlassian.net/browse/PP-380)**

#### Problem description
* Update .gitignore to ignore gtags and PBSTestLab generated files and directory

#### Cause / Analysis
* gtags is used by many developers to tag source code for easy navigation. 
This requires to create gtags database file at project root. Similarly PBSTestlab generates dir/files fw/build & tests/ptl_test_results.html . These files and directory are not part of pbs project  hence should be ignored by git.

#### Solution description
* Updating the .gitignore 

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

generated files and directory

### CODE REVIEW

**Comment by bhroam** [comment]
I sign off.  Could you update the pull request subject to include the ticket id?  PP-380: Update .gitignore to ignore files auto-generated by gtags and PBSTestLab

**Comment by bhroam** [comment]
Thanks for updating the pull request subject.  Once you get your second reviewer, you'll need to rebase your branch with master and clear up the conflicts.

**Comment by arungrover** [comment]
I sign-off on this change

**Comment by dilip-krishnan** [comment]
Hi Bhroam,
I've rebased my branch. :)

**Comment by bhroam** [comment]
Dilip, 
It unfortunately looks like something snuck after you rebased.  Your branch is out of date again.  Please rebase again.

**Comment by subhasisb** [comment]
I reviewed the code and it looks ok as well. No PTL tests necessary as this is not a code change.
Merging.

**Pull request merged**
