### PR TITLE
Fixed suppress_email=-1 support for qdel

### PR DESCRIPTION
**Pull request by alexis-cousein**
#### Describe Bug or Feature

[Note: an Altair customer asked Altair to log this as a bug, and PBS-24560 was assigned to the bug]
The Admin Guide states:

-Wsuppress_email=<N>
Sets limit on number of emails sent when deleting multiple jobs or subjobs.
• If N >= 1 and N or more job IDs are given, N emails are sent.
• If N >=1 and less than N job identifiers are given, the number of emails is the same as the number of jobs.
• If N = 0, this option is ignored.
• If N = -1, no mail is sent.

But -Wsuppress_email=-1 does not work.

The implementation without this fix suppresses mails once the number of deleted jobs reaches the supplied N exactly. Obviously, since we start with 0 deleted jobs this never "reaches" -1 exactly, so mails are not suppressed.

#### Describe Your Change

Change the comparison to check whether the number of deleted mails is *greater than or* equal to the number of deleted jobs. Added a boolean to track whether we already added "nomail" to the args passed to the server, to avoid the new comparison operator to add "nomail" more than once.

Also fixed/added some comments and added a missing #include <unistd.h> (for POSIX conformant code and according to the Linux man page, when using "getopt" you should include this header.) 

#### Link to Design Doc

N/A

#### Attach Test and Valgrind Logs/Output

No PTL test was added, since demonstration of the bug relies on a mail system -- it is unknown whether the test harness has mails correctly set up.

Here is a a screen session demonstrating the bug, and also demonstrating that a binary built from the proposed fixes does not exhibit the same problem. Comments added inline between square brackets.

```
alexis@tc72host:/sys/fs/cgroup/cpu> cd
alexis@tc72host:~> qsub -J 1-3 -- /bin/sleep 1000  
209[].tc72
alexis@tc72host:~> qdel -Wsuppress_email=-1 209[]
alexis@tc72host:~> mail
No mail for alexis
```
[Normal -- if a user deletes his own jobs, no mail is sent.]
```
alexis@tc72host:~> qsub -J 1-3 -- /bin/sleep 1000
210[].tc72
alexis@tc72host:~> sudo `which qdel` -Wsuppress_email=-1 210[]
alexis@tc72host:~> mail
Heirloom mailx version 12.5 7/5/10.  Type ? for help.
"/var/spool/mail/alexis": 1 message 1 new
>N  1 adm@tc72host.hpcgl Thu Mar 26 09:45   16/569   PBS JOB 210[].tc72
? h
>N  1 adm@tc72host.hpcgl Thu Mar 26 09:45   16/569   PBS JOB 210[].tc72
? q
Held 1 message in /var/spool/mail/alexis
```
[when root deletes a job of alexis, mails is normally sent. Suppress_email should have suppressed the mail but did not]
```
alexis@tc72host:~> qsub -J 1-3 -- /bin/sleep 1000              
211[].tc72
alexis@tc72host:~> sudo /home/alexis/cases/Thomas/qdel -Wsuppress_email=-1 211
qdel: Unknown Job Id 211.tc72
You have mail in /var/spool/mail/alexis
alexis@tc72host:~> sudo /home/alexis/cases/Thomas/qdel -Wsuppress_email=-1 211[]
alexis@tc72host:~> mail
Heirloom mailx version 12.5 7/5/10.  Type ? for help.
"/var/spool/mail/alexis": 1 message 1 unread
>U  1 adm@tc72host.hpcgl Thu Mar 26 09:45   17/579   PBS JOB 210[].tc72
? h
>U  1 adm@tc72host.hpcgl Thu Mar 26 09:45   17/579   PBS JOB 210[].tc72
? q
Held 1 message in /var/spool/mail/alexis
```
[No new mail for job array 211[] with modified binary]
```
alexis@tc72host:~> qsub -J 1-3 -- /bin/sleep 1000                              
212[].tc72
alexis@tc72host:~> sudo /home/alexis/cases/Thomas/qdel -Wsuppress_email=1 212[]  
alexis@tc72host:~> mail
Heirloom mailx version 12.5 7/5/10.  Type ? for help.
"/var/spool/mail/alexis": 2 messages 1 new 2 unread
U  1 adm@tc72host.hpcgl Thu Mar 26 09:45   17/579   PBS JOB 210[].tc72
>N  2 adm@tc72host.hpcgl Thu Mar 26 10:01   16/569   PBS JOB 212[].tc72
? h
U  1 adm@tc72host.hpcgl Thu Mar 26 09:45   17/579   PBS JOB 210[].tc72
>N  2 adm@tc72host.hpcgl Thu Mar 26 10:01   16/569   PBS JOB 212[].tc72
```
[Just to confirm that the new binary does not _always_ suppress emails -- here we do get 1 mail for 2121[] ]

image

### CODE REVIEW

**Comment by hirenvadalia** [comment]
Hey @alexis-cousein, one question, when root (or any other user who has permission to delete other users' job) (aka non-job owner-user) deletes job with suppress_email=-1 (and qsub -m is set to 'a' (which is default as of now)) then how job owner will know why his/her job is deleted?

**Comment by alexis-cousein** [comment]
> Hey @alexis-cousein, one question, when root (or any other user who has permission to delete other users' job) (aka non-job owner-user) deletes job with suppress_email=-1 (and qsub -m is set to 'a' (which is default as of now)) then how job owner will know why his/her job is deleted?

That is slightly out of scope (the documentation is clear about the desired behaviour of suppress_email). But if a site admin does this and you have job history enabled, he can see that his job is in state F without having been run, or after having been terminated. I assume they will then contact their site admin.

tracejob on the server wil also reveal the source of the request (assuming users have access to the server):

alexis@tc72host:~/git/github/alexis-cousein/pbspro/src/cmds> tracejob 213[]

Job: 213[].tc72

03/26/2020 11:33:32  L    Considering job to run
03/26/2020 11:33:32  S    enqueuing into workq, state 1 hop 1
03/26/2020 11:33:32  S    Job Queued at request of alexis@tc72host, owner = alexis@tc72host, job name = STDIN, queue = workq
03/26/2020 11:33:32  S    Job Modified at request of Scheduler@tc72host
03/26/2020 11:34:07  S    delete job request received
03/26/2020 11:34:07  S    Job to be deleted at request of root@tc72host

In fact, suppress_email is used at sites to ENSURE that users will contact site admins -- or in some other cases, to delete jobs after they have sent e-mail out-of-band to the user. If not, the site admin can always use suppress_email=N with a strict positive N.

**Comment by alexis-cousein** [comment]
@hirenvadalia it looks like the build system for the Kerberos build is broken -- this is unrelated to this change; the build machine apparently cannot reach the repository servers; it's a network issue.

+ yum -y update
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirrors.advancedhosters.com
 * epel: reflector.westga.edu
 * extras: mirrors.advancedhosters.com
 * updates: mirrors.advancedhosters.com
https://cbs.centos.org/repos/storage7-testing/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 
https://wiki.centos.org/yum-errors

**Comment by hirenvadalia** [comment]
> @hirenvadalia it looks like the build system for the Kerberos build is broken -- this is unrelated to this change; the build machine apparently cannot reach the repository servers; it's a network issue.
> 
> * yum -y update
>   Loaded plugins: fastestmirror, ovl
>   Loading mirror speeds from cached hostfile
> 
> * base: mirrors.advancedhosters.com
> * epel: reflector.westga.edu
> * extras: mirrors.advancedhosters.com
> * updates: mirrors.advancedhosters.com
>   https://cbs.centos.org/repos/storage7-testing/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
>   Trying other mirror.
>   To address this issue please refer to the below wiki article
>   https://wiki.centos.org/yum-errors

Yes @alexis-cousein, we have already one PR (https://github.com/PBSPro/pbspro/pull/1607) in-progress to fix that

**Comment by alexis-cousein** [comment]
Rebased on new upstream/master and force pushed to get rid of that Travis build environment error...

**Comment by mike0042** [comment]
Confirmed changes are identical after rebase.

**Pull request merged**
