### PR TITLE
PP-785: PTL should use same version as PBS

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Issue-ID

* **[PP-785](https://pbspro.atlassian.net/browse/PP-785)**

#### Problem description
* PTL has different version than PBS, but PTL should have same version as PBS

#### Cause / Analysis
* PTL has it's own versioning scheme than PBS, that's why it has different version 

#### Solution description
* Change PTL version to same as PBS

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by anamikau** [comment]
Hi Hiren, is this the right approach? you are hard coding the version. Every time (for patches and all) we have to patch PTL as well to update the version. Why not read the version from PBS and display it?
Also I know we decided internally to use same PBS version for PTL but just thinking loud if we need a forum discussion on that (and also an EDD).

**Comment by hirenvadalia** [comment]
@anamikau You mean when pbs_benchpress --version it should run qstat --version and return output as it is?

**Comment by anamikau** [comment]
@hirenvadalia that's implementation. qstat --version also returns builds which we don't want (I guess). But if I am running PTL from 14.2.1 branch then it should return 14.2.1, similarly for patches like 14.2.2 or 14.2.3 it should return the same. Same thing should apply for OSS (if possible).

**Comment by hirenvadalia** [comment]
@anamikau Yes I am taking about implementation only, because I totally understand your point and also understand design of how PTL version should be reported. But what you are asking is only possible when you run configure before installing PTL or if you have PBS installed in system, means external dependency. If other reviewers are fine with that I will go ahead and will make change.

**Comment by agrawalravi90** [comment]
If I understand things correctly, I think we will need to first make PTL install-able via the PBS install process before we can make this integration.
So, can this ticket wait till we make PTL install-able via the PBS install process?

**Comment by anamikau** [comment]
@hirenvadalia and @agrawalravi90, this sounds like we need a forum discussion for this.

**Comment by agrawalravi90** [comment]
Hmm .. in my view, we already know what we need to do, we need to make PTL install-able via the PBS install process and we need to have the PTL version match PBS version, so I'm not so sure that this needs a forum discussion. There will be a discussion for making PTL install-able via the PBS install process when https://pbspro.atlassian.net/browse/PP-782 gets worked on. But other than that, for this PR, I think we just need to decide if we can wait until PP-782 gets checked-in, or if this needs to go in sooner than that. If it does need to go in sooner than PP-782, then I don't think that we have any option, it will need to get done the way Hiren has implemented it now. What do you think?

**Comment by bhroam** [comment]
How about we set the version the same way we set PBS's version.  We have configure create convert a .in file that has the version in it.  The build process is already using  configure --set-version.  Why don't we just piggyback on that?  This way we will be assured to have the same version for PBS as for PTL.

**Comment by hirenvadalia** [comment]
Closing this PR since there is discussion happening on design and implementation for this and will re-open once we are ready for review.

**Pull request closed without merging**
