### PR TITLE
PP-1211: Using eligible_time, parent array job misses the stime, comment, and …

### PR DESCRIPTION
**Pull request by vchlum**
…'S' accounting record.

#### Bug/feature Description
* Parent array job misses the stime, comment, and 'S' accounting record with eligible_time_enable = True.
* [PP-1211](https://pbspro.atlassian.net/browse/PP-1211)

#### Affected Platform(s) and PBS Version
* Platform: all, tested on debian
* Bugs: 18.1

#### Cause / Analysis / Design
* The routine for setting stime, comment, and 'S' record of parent job is called once the first subjob is started and the parent job turns to 'B' too. The routine is in complete_running().
* The problem is following: with eligible_time_enable enabled the req_modifyjob() is called before complete_running(). req_modifyjob() calls svr_evaljobstate(), which sets the parent array job to 'B', therefore the complete_running() do nothing because the parent job state is already 'B'. 

#### Solution Description
* Since svr_evaljobstate() is called from plenty of places, I decided to extend the condition in complete_running(): If the stime is **not** set and the parent job is in 'B' then we still process the routine in complete_running() because this is the first time we call complete_running() for a subjob of a particular arrayjob.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [x] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by vstumpf** [comment]
LGTM

Please attach the test logs to the pull request.

**Comment by vchlum** [comment]
[PP-1211_ptl_output.txt](https://github.com/PBSPro/pbspro/files/1674443/PP-1211_ptl_output.txt)

**Comment by mike0042** [comment]
Please rebase for merge.

**Comment by vchlum** [comment]
@mike0042 Rebased. It is ready for merge.

**Pull request merged**
