### PR TITLE
PP-402: Fix Error 319 fatal error LNK1181: can not open input file "netlibtoc.lib" server

### PR DESCRIPTION
**Pull request by lcnja**
#### Issue-ID

* **[PP-402](https://pbspro.atlassian.net/browse/PP-402)**

#### Problem description
* Error 319 fatal error LNK1181: can not open input file "netlibtoc.lib" server

#### Cause / Analysis
* Incorrect Dependencies

#### Solution description
* Kindly remove Incorrect Dependencies from the windows project files. 

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by gajendrasharmagit** [comment]
Thanks for looking into this. You may also remove dependency for liblmx-altair.lib.

**Comment by gajendrasharmagit** [comment]
There are other references to LMX lib, yet to be removed from the code.

**Comment by gajendrasharmagit** [comment]
Please also remove LMX references from "Additional include directories".

**Comment by lcnja** [comment]
where,I can not find it,Please tell me,thanks

**Comment by lcnja** [comment]
[root@centos pbspro]# find . -type f|xargs grep "lmx"|grep -v '.git'                                  
./src/lib/Libdis/dis.c: if (dis_lmx10 == 0)                                                           
./src/lib/Libdis/dis_.h:extern unsigned dis_lmx10;                                                    
./src/lib/Libdis/disi10l_.c:unsigned dis_lmx10 = 0;                                                   
./src/lib/Libdis/disi10l_.c: *  dis_lmx10 equal to the largest value of n that fits the format.       
./src/lib/Libdis/disi10l_.c:    assert(dis_lmx10 == 0);                                               
./src/lib/Libdis/disi10l_.c:            dis_lmx10++;                                                  
./src/lib/Libdis/disi10l_.c:    tabsize = (dis_lmx10 + 1) * sizeof(dis_long_double_t);                
./src/lib/Libdis/disi10l_.c:    assert(dis_lmx10 > 0);                                                
./src/lib/Libdis/disi10l_.c:    for (i = 1; i <= dis_lmx10; i++) {                                    
./src/lib/Libdis/disp10l_.c:    /* dis_lmx10 would be initialized by prior call to dis_init_tables */ 
./src/lib/Libdis/disp10l_.c:                            if (++pow2 > dis_lmx10)                       
./src/lib/Libdis/disp10l_.c:    } while (pow2++ < dis_lmx10);                                         
./src/lib/Libdis/diswl_.c:      /* dis_lmx10 would be initialized by prior call to dis_init_tables */ 
./src/lib/Libdis/diswl_.c:      pow2 = dis_lmx10 + 1;                                                 
[root@centos pbspro]#

**Comment by gajendrasharmagit** [comment]
You are using a wrong version of server.vcproj file, it still shows dependency to python25. You need to Take the latest version of the file. Also you just need to remove reference to LMX in pbs_migration_asistant.bat, not remove the file altogether.

**Comment by gajendrasharmagit** [comment]
You can find the reference to include file here:
AdditionalIncludeDirectories=c:\Program Files\LM-X\include&quot;

**Comment by gajendrasharmagit** [comment]
One of your commit is not signed.

**Pull request closed without merging**
