### PR TITLE
Create job purge as different process on mom end

### PR DESCRIPTION
**Pull request by Bhagat-Rajput**
#### Bug/feature Description
* Create job purge as different process on mom end

#### Affected Platform(s)
* All (except windows)

#### Solution Description
* Creating a separate process to delete all the job related files (i.e. job script file, job control file etc.) only if the job has finished it's execution successfully.

#### Testing logs/output
* PTL logs: [ptl_job_purge.txt](https://github.com/PBSPro/pbspro/files/2626308/ptl_job_purge.txt)

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [x] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by Bhagat-Rajput** [comment]
Thanks @bhroam and @nithinj  for the sign-off. I've rebased it and ready to merge.

**Comment by alexis-cousein** [comment]
"I think this race condition is pretty small, so I'm not sure you want to worry about it."

Famous last words - see https://jira.prog.altair.com/browse/PBS-22305 

I just encountered it on a test server doing what a customer does. If you reject a job but then the scheduler decides to try to run the job again, on the same nodes, the cleanup of the abortive attempt clashes with the new attempt to create the job on mother superior.

What was the rationale for splitting off the deletion of the file? Would the aim still be achieved if the main MoM first _moved_ the files, so that the child could then remove files whose names would not clash with those of a new attempt to run the job?

**Comment by bhroam** [comment]
@alexis-cousein please don't include links to internal Altair tools.  I removed the link.

**Comment by alexis-cousein** [comment]
> On 5 Apr 2019, at 01:07, Bhroam Mann <notifications@github.com> wrote:
> 
> @alexis-cousein please don't include links to internal Altair tools. I removed the link
> 

Can I still mention the JIRA ticket in future, or would you rather not?

**Comment by bhroam** [comment]
Since this is an open source forum, we shouldn't use internal identifiers.  If you need to link to Jira tickets, please use an internal email.

**Pull request merged**
