### PR TITLE
Add sanitize build support in Travis

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Bug/feature Description
* *This PR adds support for running test under sanitized build*
* *Sanitize build helps to find memory errors in code, for more details see [here](https://github.com/google/sanitizers/wiki/AddressSanitizer)*

#### Affected Platform(s)
* *CentOS*

#### Cause / Analysis / Design
* *None*

#### Solution Description
* *Changed Travis script to do sanitize build and test*

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by agrawalravi90** [comment]
Thanks for the contribution. The pull request doesn't mention why this is being done. Could you please briefly explain how this change will help improve Travis CI builds?
Also, I'm a bit concerned about increased build times because of this, could you please tell us if this will increase the Travis build times and by how much?

**Comment by hirenvadalia** [comment]
@agrawalravi90 This is not about improving Travis CI. We are adding support for running test under sanitize build. And I hope you know what is sanitize build, which will help us to catch memory errors.

And this will not increase travis build time, as you can see for this PR it took ~18 min to complete build and test under sanitize build while for normal build it took ~14-16 min.

HTH!

**Comment by agrawalravi90** [comment]
Thanks for clarifying Hiren. It increases the CI time for CentOS7 by ~3 mins, which should be fine I guess.

And yes, I personally do know what -fsanitize does, but I didn't know about it until recently, so I thought it'd help the uninitiated if there were more details in the PR, but it's upto you and your reviewers. Thanks again for the contribution.

**Comment by subhasisb** [comment]
@hirenvadalia i think adding the motivation to the description is a fine suggestion.

**Comment by hirenvadalia** [comment]
@agrawalravi90 and @subhasisb I have added one line motivation to description, please let me know if you want to add more.

**Comment by agrawalravi90** [comment]
Looks good to me, thanks for adding the details.

**Comment by subhasisb** [comment]
Hiren please squash and rebase

**Comment by hirenvadalia** [comment]
@subhasisb Rebased and squashed, its ready for merge.

**Pull request merged**
