### PR TITLE
Additional tests for prime and dedicated queues and qmgr sched attrs

### PR DESCRIPTION
**Pull request by visheshh**
#### Bug/feature Description
Additional tests for prime and dedicated queues and qmgr scheduler attributes

#### Affected Platform(s)
All Platforms

#### Solution Description
Added tests for prime and dedicated queues with partitions and a non default scheduler serving them
Added tests for verify issue non default schedulers were querying default scheduler attributes

#### Testing logs

[ptl_multisched_logs.txt](https://github.com/PBSPro/pbspro/files/1832242/ptl_multisched_logs.txt)

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [x] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by arungrover** [comment]
@visheshh  change looks good, please rebase after you get another sign-off

**Comment by visheshh** [comment]
squashed and rebased

**Comment by mike0042** [comment]
Is there a log of the tests being run? Please attach it to the PR.

**Comment by visheshh** [comment]
attached testing logs : 
[ptl_multisched_logs.txt](https://github.com/PBSPro/pbspro/files/1832244/ptl_multisched_logs.txt)

**Comment by visheshh** [comment]
rebased again

**Pull request merged**
