### PR TITLE
PP-254: merging doxygen changes for pending files

### PR DESCRIPTION
**Pull request by nithinj**
#### Issue
* PP-254

#### Problem
* Many files are not showing up in the generated doxygen report.

#### Cause
* "@file" command was not added in the missing files.

#### Solution
* comment block with @file should be included in the files.

### CODE REVIEW

**Comment by crjayadev** [comment]
The files looks mostly fine but to be consistent please use the following all across

@File file_name
@Brief short_summary
@par for description with a title for the paragraph
@note for special notes

**Comment by nithinj** [comment]
I have made necessary changes to make doxygen directive usage to be consistent across files. Please go through the change list.

**Comment by crjayadev** [comment]
Looks good. I sign off.

**Comment by bremanandjk** [comment]
Looks good. I sign off.

**Pull request merged**
