### PR TITLE
PP-370: Update pull request template to explicitly clarify about PTL/…

### PR DESCRIPTION
**Pull request by subhasisb**
Modifying the pull request template such that it explicitly mentions about PTL/manual tests and where to add them etc.

This is how the template looks now:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

#### Issue-ID

* PP-XXXX

#### Problem description
* Describe the issue being fixed

#### Cause / Analysis
* Briefly describe root cause/analysis of the problem

#### Solution description
* Please describe your changes in detail for reviewers

#### Checklist:

- [ ] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [ ] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [ ] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by iestockdale** [comment]
@subhasisb, this looks good.  I sign off.

**Comment by ashwathraop** [comment]
@subhasisb change looks fine to me. I sign-off.

**Comment by crjayadev** [comment]
The template looks good.

**Comment by arungrover** [comment]
All looks good. Merged

**Pull request merged**
