### PR TITLE
PP-942: Compilation failure when -DDEBUG is defined

### PR DESCRIPTION
**Pull request by nithinj**
#### Issue-ID

* **[PP-942](https://pbspro.atlassian.net/browse/PP-942)**

#### Problem description
* Compilation failure when -DDEBUG is defined

#### Cause / Analysis
* typos lead to compilation error.

#### Solution description
* Fixed the typo and replaced `id` with `__func__`

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

CC: @subhasisb

### CODE REVIEW

**Comment by mike0042** [comment]
Please rebase your branch in preparation for merge.

**Comment by bhroam** [comment]
Looks good to me.  I sign off.

**Comment by nithinj** [comment]
Thanks @mike0042 and @bhroam for your sign-off.
I've re-based my branch. Please take this further.

**Comment by mike0042** [comment]
Looks like something else got merged. Please rebase @nithinj

**Comment by nithinj** [comment]
Hi @mike0042 ,
I've re-based it. Please check.

**Comment by bhroam** [comment]
I've merged in this PR.

**Pull request merged**
