### PR TITLE
Resolve req_resvSub() memory leak

### PR DESCRIPTION
**Pull request by ashwathraop**
#### Bug/feature Description
* Memory leak during reservation submission with wall time requests*

#### Affected Platform(s)
* All

#### Cause / Analysis / Design
* When a reservation is submitted with wall time requests PBS errors out without freeing the memory allocated to hold the reservation information

#### Solution Description
* Free the memory before we send req_reject()

#### Testing logs/output
[reservation.txt](https://github.com/PBSPro/pbspro/files/2442817/reservation.txt)
[resv_start_end.txt](https://github.com/PBSPro/pbspro/files/2442818/resv_start_end.txt)
[smoke.txt](https://github.com/PBSPro/pbspro/files/2442819/smoke.txt)

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by ashwathraop** [comment]
[after_pbs_server.bin_1538105661_REDHAT7.txt](https://github.com/PBSPro/pbspro/files/2444828/after_pbs_server.bin_1538105661_REDHAT7.txt)
[before_fix_pbs_server.bin_1536916275_RHEL7.txt](https://github.com/PBSPro/pbspro/files/2444829/before_fix_pbs_server.bin_1536916275_RHEL7.txt)
Here are the valgrind logs.

**Comment by ashwathraop** [comment]
[before_the_fix.txt](https://github.com/PBSPro/pbspro/files/2446638/before_the_fix.txt)
One more version for valgrind logs before the fix.

**Comment by arungrover** [comment]
Thanks Ashwath for posting the logs.
Please the the branch.

**Comment by ashwathraop** [comment]
Rebased the branch. @arungrover please take it forward. Thanks.

**Pull request merged**
