### PR TITLE
PP-418: pbs_password fails to create or update user password

### PR DESCRIPTION
**Pull request by gajendrasharmagit**
#### Issue-ID

* **[PP-418](https://pbspro.atlassian.net/browse/PP-418)**

#### Problem description
* pbs_password fails to update or create user credentials on Windows platform.

#### Cause / Analysis
* pbs_password must use AES encryption to encrypt the credential. While it does, it reports that wrong credential type while sending PBS_BATCH_UserCred requests.

#### Solution description
* pbs_password will now send the PBS_BATCH_UserCred request to server with correct credential type i.e. PBS_CREDTYPE_AES.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by mike0042** [comment]
Just merged a change from Anamika. Please update your branch.

**Comment by mike0042** [comment]
And please sign your pull request.

**Comment by gajendrasharmagit** [comment]
Please check now.

**Comment by bayucan** [comment]
Changes looked fine. I sign off.

**Comment by gajendrasharmagit** [comment]
Can one of the integrators, take this forward?

**Pull request merged**
