### PR TITLE
PP-82: After qordering the jobs, jobs are not considered in the corre…

### PR DESCRIPTION
**Pull request by vinodchitrali**
#### Issue-ID

* **[PP-82](https://pbspro.atlassian.net/browse/PP-82)**

#### Problem description
* When one does qorder on two jobs the order in which we see the job changes but the order in which the jobs are picked to run doesn't

#### Cause / Analysis
* This was because scheduler to stabilize a sort (i.e. after apply all sorting alogorithms when both the jobs turn out to be same) sorts jobs on the basis on qtime of the job. This makes scheduler select the job which was submitted first to run first and qorder has no effect.

#### Solution description
* Now scheduler sorts on a new job attribute that stores the same qtime when a job is queued but upon qorder we swap the value of this attribute and the correct job gets picked up to sort.
The way that we stabilize the sort has also changed, scheduler now sorts on this new job attribute to stabilize the sort and if they value turns out to be same then it goes back and compares job rank given to each job by scheduler.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [x] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

…ct order

### CODE REVIEW

**Comment by arungrover** [comment]
Vinod, change looks good.

**Comment by suresh-thelkar** [comment]
Code changes look good to me. I sign off.

**Comment by vinodchitrali** [comment]
Already squashed to single commit.

**Comment by vinodchitrali** [comment]
re-based

**Comment by subhasisb** [comment]
Everything looks good - merging.

**Pull request merged**
