### PR TITLE
PP-855: PTL uses wrong default path for PBS_HOME

### PR DESCRIPTION
**Pull request by Bhagat-Rajput**
#### Bug/feature Description
* PTL uses wrong default path for PBS_HOME 
* [PP-855](https://pbspro.atlassian.net/browse/PP-855)

#### Affected Platform(s)
* All Platforms

#### Cause / Analysis / Design
* In OSS default home path is (/var/spool/pbs/) but at some places have found (/var/spool/PBS/), it causes failure

#### Solution Description
* Changed default home path /var/spool/PBS/ to /var/spool/pbs/

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by Bhagat-Rajput** [comment]
Rebased and ready to merge.

**Comment by mike0042** [comment]
Another PR just got merged. Please rebase once again.

**Comment by Bhagat-Rajput** [comment]
Rebased.

**Comment by mike0042** [comment]
TravisCI seems to be having problems.

**Pull request merged**
