### PR TITLE
Making logging to asynchronous for the daemons

### PR DESCRIPTION
**Pull request by sakshamgarg**
#### Bug/feature Description
* *Making logging to asynchronous for all the daemons*

#### Affected Platform(s)
* *ALL*

#### Cause / Analysis / Design
* *In scenarios where the system has slow disk, having synchronous logging might negatively effect the performance of PBSPro.*

#### Solution Description
* *Making it asynchronous by removing fflush() function*

#### Testing logs/output
* **

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by subhasisb** [comment]
Thanks. I like the change. 

So, even if PBS dies abruptly, the stuff it has written to the kernel buffers will get written to disk in the next unix sync cycle. Also this change affects only the daemon logs and not the accounting logs. The only case where we might lose log information is when the host itself loses power etc. However, even in that case, with synchronous logging too, we would have lost log entries.

**Comment by subhasisb** [comment]
One easy way to test this would be to host pbs home on a NFS or similar slow file system.

**Comment by sakshamgarg** [comment]
@suresh-thelkar  I tested on windows platform also. It is working fine.

**Comment by Shrini-h** [comment]
The title is a bit misleading, the logging is still synchronous. You are just reducing the number of buffer flushes to the kernel file streams.
If you don't find performance improvements in your test on NFS or slower FS, then we should think about making it really asynchronous.

**Comment by sakshamgarg** [comment]
Hi @subhasisb @agrawalravi90 . 
I tested by setting hosting PBS_HOME on a NFS system as suggested by @subhasisb . I ran 1000 jobs with 10 moms. It took 83 seconds to run 1000 jobs on my branch as compared to 117 seconds on the current master branch. 
So it is showing improvement of approximately 29%.

**Comment by agrawalravi90** [comment]
Thanks for posting the results Saksham, can you please address @Shrini-h 's comments?

**Comment by sakshamgarg** [comment]
@Shrini-h  The logging does become asynchronous as fflush function do wait till it gets a confirmation that all the data from buffer has been written to the disk. In this sense it is not synchronous.

**Comment by agrawalravi90** [comment]
@subhasisb are you happy with the test results that Saksham posted?

**Comment by subhasisb** [comment]
@agrawalravi90 i am happy with the test results. I think if we get access to a slower device the difference will show more prominently, but this shows there is a difference and that's what matters for this minor change.

**Comment by anamikau** [comment]
I posted the testing logs to the summary section. It is hard to scroll to the comments to find the test results.

**Comment by sakshamgarg** [comment]
> I posted the testing logs to the summary section. It is hard to scroll to the comments to find the test results.

Thanks @anamikau . I will take care about that from next time.

**Pull request merged**
