### PR TITLE
PP-510: Libpbs,server makefile repair python call from environment variable P…

### PR DESCRIPTION
**Pull request by honza801**
#### Issue-ID

* **[PP-510](https://pbspro.atlassian.net/browse/PP-510)**

#### Problem description
* cannot compile on systems with python 3 as default version

#### Cause / Analysis
* makefiles does not respect PYTHON variable correctly

#### Solution description
* replace python calls in makefiles src/server/Makefile.am and src/lib/Libpbs/Makefile.am according to PYTHON variable

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by arungrover** [comment]
@honza801 Thanks for your contribution!
I'd request you to join the pbspro community forum and also put compilation logs on the JIRA ticket for us to work on this ticket further.
If you have already done these two things then please mark it as checked in the checklist of the pull request.

**Comment by bhroam** [comment]
Thanks for the contribution.  I sign off on the change.

**Comment by arungrover** [comment]
Hi @honza801, I see that you marked the checklist item about attaching log files on the Jira ticket; But, I do not see anything attached to the ticket. Can you please check once more?

**Comment by honza801** [comment]
hi @arungrover,

i have included only relevant parts of compilation logs. should i attach whole `make` output?

jan

**Comment by arungrover** [comment]
Hi @honza801,

I'm somehow not able to find the make logs on the ticket. I do see the logs depicting the issue but no logs depicting that it's compiling fine. Only attaching relevant compilation logs would be just sufficient.

Thanks,
Arun

**Comment by honza801** [comment]
@arungrover autogen, configure, make logs are now attached.

jan

**Comment by arungrover** [comment]
Thank you @honza801 for attaching the logs! 
I've assigned the ticket to you. Your change looks good. 
Please rebase your branch once for it to be merged.

**Comment by honza801** [comment]
ok, this went bad :)

"Update" icon did not make what i expected. should i create another branch, or is there any onter way to correct this unsigned commits insanity?

jan

**Comment by arungrover** [comment]
I'd suggest that you squash all these commits into one... rebase it with the latest master branch and after a successful rebase, sign it using 'git commit --amend' and then push it back. 
This "[How to](https://pbspro.atlassian.net/wiki/display/DG/How-tos%3A+Git)" guide might come in handy.

**Comment by honza801** [comment]
this cannot pass in travis, because there are unsigned commits in history.
Running check: 'checksign' ... FAILED

fous

**Comment by arungrover** [comment]
@honza801  there is another way to fix it.
Bring your master in sync with pbspro master.
Reset you branch HEAD to dce0a2e (this was your initial commit hash)
and then rebase your branch with your master.

This will resolve your problems with commits, I'd suggest not to use "Update" icon and do it using command line tools.

**Comment by subhasisb** [comment]
@honza801 you can also find more help here: https://pbspro.atlassian.net/wiki/display/DG/How+to+Squash+Git+Commits

**Comment by honza801** [comment]
finally, the rebase went ok.

**Comment by arungrover** [comment]
All looks good, merging it in.

**Pull request merged**
