### PR TITLE
PP-1144: PTL-Interactive job timeout if jobid has FQDN hostname

### PR DESCRIPTION
**Pull request by kjakkali**
#### Issue-ID

* **[PP-1144](https://pbspro.atlassian.net/browse/PP-1144)**

#### Problem description
* In PTL interactive job timeout if jobid has FQDN hostname.

#### Cause / Analysis
* The regex to match job id was not handling hostname with FQDN

#### Solution description
* Updated jobid matching regex to consider hostname with FQDN

In PTL the regex to get interactive job id does not honor hostname with FQDN.

EX:
1 . working example
mom02:/home/kumarj # /opt/pbs/bin/qsub -I
qsub: waiting for job 0.mom02 to start
qsub: job 0mom02 ready

2. Timeout example
mom02:/home/kumarj #/opt/pbs/bin/qsub -I
qsub: waiting for job 0.mom02.pbstest.com to start
qsub: job 0.mom02.pbstest.com ready

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
Please rebase for the final merge.

**Comment by kjakkali** [comment]
@bhroam  : Thank you. I have rebased my branch.

**Comment by kjakkali** [comment]
@bhroam :  I have rebased my branch. Ready to merge.

**Comment by bhroam** [comment]
I merged in the PR.

**Pull request merged**
