### PR TITLE
PP-865: PTL doesn't unassociate nodes from queues in revert_to_defaul…

### PR DESCRIPTION
**Pull request by borlesanket**
#### Issue-ID

* **[PP-865](https://pbspro.atlassian.net/browse/PP-865)**

#### Problem description
* During Server revert to default test fails if the node is associated with the particular queue with the error ['qmgr obj=nodes_queue svr=default: Cannot delete busy object', 'qmgr: Error (15027) returned from server'] 

#### Cause / Analysis
* Inside Server's 'revert_to_defaults' during queue deletion if a queue is set on particular node then  PTL does not unassociate the node from queue before deletion.

#### Solution description
* Before deleting queues inside Server revert to default, we need to check if any queue is associated with any node and if yes then we should unset the queue before deleting it.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
The code change looks fine.  If you wanted to go one spec further, you could remove the work around several tests took.  Both pbs_nodes_queues.py and pbs_equiv_classes.py unset the queue attribute on the node.  It isn't necessary, but it might be nice.

**Comment by borlesanket** [comment]
@bhroam , I have removed the workaround done in pbs_nodes_queues.py and pbs_equiv_classes.py, pleas e review.

**Comment by borlesanket** [comment]
@bhroam , I have rebased the branch and its ready for merge.

**Comment by bhroam** [comment]
I merged in the PR.

**Pull request merged**
