### PR TITLE
PP-379: Systemd pbs unit file should refer path from pbs.conf file

### PR DESCRIPTION
**Pull request by nithinj**
#### Issue-ID

* **[PP-379](https://pbspro.atlassian.net/browse/PP-379)**

#### Problem description
* Systemd pbs unit file should refer path from pbs.conf file

#### Cause / Analysis
* PBS_EXEC can be changed while installing rpm, this will override the path passed during configure. But unit file refers to the earlier path for starting PBS. This has to be updated using post_install script.

#### Solution description
    updated post_install script to update exec_path
    .travis.yml updated to keep the syntax of PTL 13.1 release notes
    pbspro.spec updated to avoid error in non-systemd platforms.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bremanandjk** [comment]
I sign-off on this code changes.

**Comment by mike0042** [comment]
Travis check failed for some reason. Closing and reopening pull request to rerun checks.

**Comment by mike0042** [comment]
Please sign your pull request.

**Comment by agrawalravi90** [comment]
Travis checks failed again .. @nithinj  please investigate.

**Comment by nithinj** [comment]
amended the signature.

**Comment by mike0042** [comment]
Pull request checks indicate CLA has not been signed.

**Comment by mike0042** [comment]
Please rebase your pull request so that it is up to date with master.

**Comment by nithinj** [comment]
Rebased and made up to date.

**Pull request merged**
