### PR TITLE
PP-371: Remove AIX specific netwins resource and PBS_ibwins hook

### PR DESCRIPTION
**Pull request by gajendrasharmagit**
#### Issue-ID

* **[PP-371](https://pbspro.atlassian.net/browse/PP-371)**

#### Problem description
* PBS Pro would no longer have support for AIX platform.

#### Cause / Analysis
* netwins resource and ibwins hook need to be removed from our interface.

#### Solution description
* Remove netwins resource and ibwins hook from PBS Pro source.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by mike0042** [comment]
If you go to the top level of the source tree and run "grep -ri aix ." you will see several remaining references to AIX, including scripts like pbs_postinstall. You'll also want to remove things like pbsrun.poe.in

**Comment by gajendrasharmagit** [comment]
Per ScottC, Bill has advised to keep the AIX references as it is for anyone wants to build Open Source on AIX. Only netwins resource and ibwins hook needs to be removed.

**Comment by gajendrasharmagit** [comment]
Please review.

**Comment by mike0042** [comment]
The title of this pull request (and the associated ticket) should be updated to accurately describe this change. Clearly, then intent is no longer to "Drop support for AIX"

**Comment by gajendrasharmagit** [comment]
Kindly update the bug PP-371 with your suggestion.

**Comment by arungrover** [comment]
Gajendra,
 
In current scenario we are deleting the whole of AIX directory altogether. I think we can keep it as is  people who intend to build it for AIX and just remove unnecessary resource (if there are any) instances from these files.
 
What do you think?

**Comment by subhasisb** [comment]
Yes, actually what we would want to do is only remove the resources, since we cannot conditionally exclude them from a Linux build. Beyond that, we would really want to keep the rest of the AIX code as-is, such that other community contributors can then provide fixes to them as they deem necessary.

**Comment by gajendrasharmagit** [comment]
As decided, I have kept the aix directory as it is. Pls review.

**Comment by gajendrasharmagit** [comment]
netwins refernces are now removed from AIX specific code as well.

**Comment by arungrover** [comment]
Change looks good to me. @gajendrasharmagit please rebase your branch.

**Comment by subhasisb** [comment]
PTL tests dont work on Windows. Also this is AIX code removal so nothing specific to test and existing PTL tests on Windows have passed.

**Pull request merged**
