### PR TITLE
PP-352: Error when unsetting ncpus, that is ['ncpus'] = None, in modi…

### PR DESCRIPTION
**Pull request by riyazhakki**
#### Issue-ID

* PP-352

#### Problem description
* Resetting the resource in modify job hook is ignored and throws an error "-lresource=" cannot be used with "select" or "place", resource is: ncpus 324.centos7-vm'

#### Cause / Analysis
* Code was not checking for the null value

#### Solution description
* Added a check to perform action only when resource has value

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [x] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

…fyjob hook

### CODE REVIEW

**Comment by bayucan** [comment]
This looks fine, I sign off.

**Comment by bhroam** [comment]
Hey Riyz,
I have a couple of questions about your test.  Why the try/except around the job submit?  Don't you want the test to error out if the job isn't submitted correctly?  The next thing you do is try and alter it.  Also, why the sleep 5?  That could introduce a race condition into the test.

**Comment by riyazhakki** [comment]
Hi Bhroam,
Yes you are right we have to allow job submission error, I have removed try/except around job submit. 
I had used sleep statement just for job to trasit from queue to held state, now I have removed it to avoid race condition. Thanks

**Comment by bhroam** [comment]
Hey Riyaz,
Thanks for making the change.  I have another question.  In the pre-fix case, will the alterjob itself fail the test?  I suspect it will, but I wanted to check.  Another observation is if you wanted to make sure your job got into the held state, you can always use a self.server.expect() on job_state.

**Comment by riyazhakki** [comment]
Hi Bhroam,
Yes alterjob will through error to fail the test. I have added self.server.expect(JOB, {'job_state': 'H'}, id=jid)
to make sure job got into held state. Thanks.

**Comment by bhroam** [comment]
Everything appears to be in order except that your branch is out of date with the base branch.  Can you rebase it with master?

**Comment by riyazhakki** [comment]
Now my branch is up to date with base branch.

**Comment by bayucan** [comment]
Looks good, I sign off.

**Comment by bhroam** [comment]
Riyaz, your branch is out of date again :(  Please rebase it with master

**Comment by riyazhakki** [comment]
Hi Bhroam, 
I did rebase with master, now you can take it forward

**Comment by bhroam** [comment]
Thanks for rebasing, Riyaz.  Everything is in order, I merged in this request.

**Comment by riyazhakki** [comment]
Thanks Bhroam

**Pull request merged**
