### PR TITLE
default_qsub_arguments -V not working (18.1)

### PR DESCRIPTION
**Pull request by mike0042**
#### Bug/feature Description
* qsub -V option is not working when it is set using default_qsub_arguments.
* Bugs: Once the default_qsub_arguments is set for -V option, "qstat -f" doesn't display environment variable except those which are related to PBS or which are set using -v option.

#### Affected Platform(s)
* All

#### Cause / Analysis / Design
* Bugs: Environment variable list is not stored after checking that -V option is set or not in default_qsub_arguments.

#### Solution Description
* After the options for default_qsub_arguments are processed, -V option is checked whether it is set or not.
* If the -V option is set then using the variable 'environ', all the environment variable are stored as a list in a variable.

#### Testing logs/output
* Forthcoming

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [X] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bayucan** [comment]
The fix generally looks fine, though, you have a Codacy error that needs to be addressed.

**Comment by mike0042** [comment]
Thanks @bayucan. I'll address the Codacy warning. It's very odd because the file in this PR and the one currently checked into master are identical. I'm also seeing a couple issues with running the pbs_passing_environment_variable.py tests I'll need to address. The smoke tests ran fine.

**Comment by subhasisb** [comment]
Something stuck with codacy and appveyor. Closing and reopening to try to get it unstuck

**Comment by mike0042** [comment]
I have addressed your comments @bayucan. I've also included the fix from https://github.com/PBSPro/pbspro/pull/712 that resolves a test failure. The Codacy warning has been addressed, but for some reason it wasn't triggered for the latest commit. Please have another look.

**Comment by mike0042** [comment]
Thanks @bayucan! I'll rebase now and request a maintainer review.

**Comment by mike0042** [comment]
@PBSPro/pbspro-maintainers : This is a time sensitive PR. Requesting a review.

**Comment by arungrover** [comment]
@mike0042  change looks good, can you please post test logs to the pull request.

**Comment by mike0042** [comment]
Test logs:
[smoketest.log](https://github.com/PBSPro/pbspro/files/2521125/smoketest.log)
[pbs_passing_environment_variable.log](https://github.com/PBSPro/pbspro/files/2521126/pbs_passing_environment_variable.log)

**Comment by mike0042** [comment]
Thanks @arungrover! PR has been squashed and test logs attached. There seem to be issues with Appveyor and Codacy today. This should be the last of the changes for 18.1.3 @subhasisb

**Comment by arungrover** [comment]
Thanks @mike0042 
In the test logs test case - Test_passing_environment_variable_via_qsub.test_passing_shell_function is failing, is it expected?

**Comment by mike0042** [comment]
Yes @arungrover, there is a ticket filed for the failing test that @anamikau pointed out.

**Comment by arungrover** [comment]
Thanks! just wanted to make sure. Please squash and rebase

**Comment by mike0042** [comment]
Thanks @arungrover. This PR has been squashed and rebased.

**Pull request merged**
