### PR TITLE
PP-738: Wrong test count displayed when PTL fails in setUpClass

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Issue-ID

* **[PP-738](https://pbspro.atlassian.net/browse/PP-738)**

#### Problem description
* test failure in setUpClass leads to wrong statistics count in summary

#### Cause / Analysis
* In python unittest framework whenever test fails in setUpClass, framework doesn't increase testsRun count which leads to negative number in summary

#### Solution description
* corrected calculation of statistics count in summary by collecting success info along with error, failure, skipped and timedout infos

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by agrawalravi90** [comment]
As Anamika suggested, could you please write a test to verify this, if possible?

**Comment by bhroam** [comment]
What is the status of this PR?  It has been lingering for some time.

**Comment by hirenvadalia** [comment]
@bhroam Sorry for late reply but I didn't get much time to get back on this issue after my vacation.
@anamikau and @agrawalravi90 I have updated ticket with before and after fix... FYI to reproduce this test need to some hack in PBSTestSuite.setUpClass as this issue is not straightforward reproducible.

**Comment by hirenvadalia** [comment]
@PBSPro/pbspro-maintainers this PR is ready for merge, please have look and let me know if anything is missing...

**Comment by bhroam** [comment]
Looks good to me.  Please rebase your branch with current master

**Comment by hirenvadalia** [comment]
@bhroam Done I have re-based branch with current master.

**Comment by arungrover** [comment]
@hirenvadalia branch is out of sync again. Please rebase.

**Comment by hirenvadalia** [comment]
@arungrover Done I have rebased again.

**Comment by agrawalravi90** [comment]
Looks good to me, merged

**Pull request merged**
