### PR TITLE
Combine related qstat tests in a single test suite

### PR DESCRIPTION
**Pull request by latha-subramanian**
#### Bug/feature Description
A couple of qstat related tests remain under different test suites.  One has to remember individual test suites during execution.

#### Affected Platform(s)
All

#### Cause / Analysis / Design
Newer tests were added to new test suites 

#### Solution Description
Combine related qstat tests in a single test suite. The tests from the following files were added to a single test suite TestQstatFormats in pbs_qstat_formats.py (22 tests).  Also added the PTL tag "commands" to the test suite.
pbs_qstat_dsv.py (12 tests)
pbs_qstat_tag.py  (1 test)
pbs_qstat_json.py (7 tests)
pbs_qstat_oneline_dsv_json.py (2 tests)
The above 4 files were removed from this directory.

Note:
Git thinks that pbs_qstat_json.py is renamed to pbs_qstat_formats.py because these two files have substantially similar content. But please note that pbs_qstat_formats.py is the new file and pbs_qstat_json.py is removed from this directory.

#### Testing logs/output

[before_qstat_oneline.txt](https://github.com/PBSPro/pbspro/files/2480187/before_qstat_oneline.txt)
[before_qstat_dsv.txt](https://github.com/PBSPro/pbspro/files/2480188/before_qstat_dsv.txt)
[before_qstat_tag.txt](https://github.com/PBSPro/pbspro/files/2480189/before_qstat_tag.txt)
[before_qstat_json.txt](https://github.com/PBSPro/pbspro/files/2480190/before_qstat_json.txt)
[afterfix_qstat_formats.txt](https://github.com/PBSPro/pbspro/files/2480194/afterfix_qstat_formats.txt)

Please note that test_qstat_bf_json_valid (pbs_qstat_json.py ) has been failing before this PR. 

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by agrawalravi90** [comment]
Looks good to me as well, please rebase for merge.

**Comment by latha-subramanian** [comment]
Thanks @lisa-altair , @agrawalravi90 .

I have squashed and rebased, ready for merge !

**Comment by arungrover** [comment]
@latha-subramanian your branch is out of sync again. Please rebase once more

**Comment by latha-subramanian** [comment]
@arungrover , I have rebased again. Please take it forward for merge.  Thanks !

**Pull request merged**
