### PR TITLE
pp-263: Hook throwing error 'SwigPyObject' object has no attribute 'n…

### PR DESCRIPTION
**Pull request by bhroam**
The pbs_ifl.py file is generated by swig. During the make process, if swig is available on the system, the file is regenerated. If swig is not available, there is a pre-generated copy that is checked into the codebase. The make dist process doesn't do a make, it just copies existing files from the source tree to the tarball. This copies the pre-generated file.

The pre-generated file was out of date. An attribute was removed from PBS recently and the pre-generated pbs_ifl.py still had a reference to it.

The fix: regenerate the pbs_ifl.py file.

The file has been stale for some time, so there will be some new additions shown in the diff.

This pull request is for the 15.0 master branch

### CODE REVIEW

**Comment by visheshh** [comment]
I sign off on this change as this new file is required . But the question still remains , Why swig is not generating the pbs_ifl.py while building pbs even though swig is available . While running make the file should have been generated , I think we need a separate ticket to fix the issue.

Thanks,
Vishesh

**Comment by subhasisb** [comment]
Closing and reopening to ensure Travis goes through (after it was fixed)

**Comment by hirenvadalia** [comment]
+1 for @visheshh's  question...
Assuming this pull is about to update out dated pbs_ifl* file: I sign-off on change.

**Comment by mike0042** [comment]
The correct fix for this issue is to remove pbs_ifl.py from the source tree. It is only there because one of the previously supported platforms did not have swig installed. This file should be deleted so that we don't run into this issue again.

**Comment by bayucan** [comment]
In response to Mike's comment about removing pbs_ifl.py: the file was put in there so that if PBS gets compiled in a platform that does not have 'swig' installed. then this file acts as a cached copy and is the one used when installed. Bhroam and I noticed that after doing 'make dist' of pbspro, we see that a correct pbs_ifl.py is re-generated because we have 'swig' in our system. But after the rpm files are generated, and pbs was installed, the installed /opt/pbs/lib/python/altair/pbs/v1/pbs_ifl.py looks like the cached copy pbs_ifl.py from source. Besides getting the cached copy updated to be consistent with the OSS source, what do we need to change to have the re-generated pbs_ifl.py on a make, be the one that gets copied to the rpm distribution for install.. That should complete the fix. Or is removing pbs_ifl.py from source would automatically take the pbs_ifl.py from target directory and put into rpm distribution?

**Comment by bayucan** [comment]
Follow-up: the regenerated pbs_ifl.py is in:

**Comment by bayucan** [comment]
The regenerated pbs_ifl.py is in <target_directory>/src/lib/Libpython. The cached source is in <source_directory>/src/lib/Libifl/pbs_ifl.py.

**Comment by bayucan** [comment]
I mean the generated pbs_ifl.py in [target_directory]/src/lib/Libpython while the cached file is in [source_directory]/src/lib/Libifl.

**Pull request merged**
