### PR TITLE
PP-960: add Dockerfile for centos7

### PR DESCRIPTION
**Pull request by minghui-liu**
#### Issue-ID

* **[PP-960](https://pbspro.atlassian.net/browse/PP-960)**

#### Description
Add Dockerfile for centos7 so that any code changes to this repo will trigger an automated build on docker hub and an image base on centos7 will be built according to this Dockefile. 

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by minghui-liu** [comment]
Travis opens use keeps failing because of network issue

**Comment by subhasisb** [comment]
An opensuse repository link is broken, Travis will continue to fail. We are investigating this issue.

**Comment by subhasisb** [comment]
Travis/Opensuse is back up now.

**Comment by subhasisb** [comment]
@minghui-liu codacy is suggesting we add a maintainer for the dockerfile. If we add that I think codacy will pass it. :)

**Comment by minghui-liu** [comment]
@subhasisb I already have a maintainer line in the dockerfile. I do not know why codacy is complaining.

**Comment by subhasisb** [comment]
@minghui-liu i think codacy has an error in this detection, so I think we should go ahead. Kindly squash your commits and we should be able to merge it in.

**Comment by minghui-liu** [comment]
@subhasisb I think codacy is looking for the deprecated `MAINTAINER` tag, which has been replaced by `LABEL maintainer`.

**Comment by minghui-liu** [comment]
@subhasisb Squashed and signed.

**Comment by agrawalravi90** [comment]
I've always seen the 'maintainer' value be an email id, that is probably not why Codacy is breaking up, but can you try providing it an email-id anyways just to see if that's what this is about?

**Comment by minghui-liu** [comment]
Sure. What email address should I use?

**Comment by agrawalravi90** [comment]
hmm ..  I don't think there's a single email id for the community. Maybe just use a dummy for now just to see if this goes away?

**Comment by agrawalravi90** [comment]
or not .. I don't think this is important .. I was just curious more than anything ..

**Comment by minghui-liu** [comment]
I put mine in for now so at least people can contact me if there is a problem with dockerfile. We can change to a community email later.

**Comment by agrawalravi90** [comment]
Thanks for trying it out, Codacy definitely seems broken here .. so it's up to you if you wanna keep your email id there or not.

**Comment by minghui-liu** [comment]
I prefer leaving it there for now. Thanks @agrawalravi90

**Comment by agrawalravi90** [comment]
Cool :) I'm afraid you'll need to squash again though, sorry about that.

**Comment by hirenvadalia** [comment]
@minghui-liu I think you need to put both LABEL field after FROM line, then codacy might become happy...
(see [this](https://docs.docker.com/engine/reference/builder/#format))

**Comment by minghui-liu** [comment]
@hirenvadalia That was what I put in the initial commit. It did not work. I think codacy is checking for the old MAINTAINER tag.

**Comment by minghui-liu** [comment]
@agrawalravi90 Squashed.

**Comment by mike0042** [comment]
Code changes look fine. Additional checklist items need to be completed prior to merge.

**Comment by minghui-liu** [comment]
I did a manual docker build to verify the Dockerfile and attached build output to JIRA ticket. Please let me know if anything else needs to be done.

**Comment by subhasisb** [comment]
I am afraid u will need to rebase again.

**Comment by minghui-liu** [comment]
Rebased.

**Comment by mike0042** [comment]
Please sign your latest commit (git commit --amend -S --no-edit) and then push your change. Travis is failing because your commit is not signed.

**Comment by minghui-liu** [comment]
I keep forgetting that. Should make signing a default for my git. Thanks @mike0042

**Pull request merged**
