### PR TITLE
PP-964: Wrong use of BASIL string size used in snprintf

### PR DESCRIPTION
**Pull request by arungrover**
#### Issue-ID

* **[PP-964](https://pbspro.atlassian.net/browse/PP-964)**

#### Problem description
During code inspection it was found that in alps.c we do not use the right buffer length while copying data received from ALPS to our internal structures. 
#### Cause / Analysis
Wrong buffer length being used
#### Solution description
Use the right buffer length.

#### NOTE
This fix can not be verified because it was found during code inspection and no static analysis tool can catch it because the length being used was less than the buffer size which isn't a crime :)

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by arungrover** [comment]
Thanks for review @lisa-altair I'll test it on a simulator and post results

**Comment by arungrover** [comment]
While trying to test the change with existing apbasil ptl test I stumbled across a PTL framework problem (https://pbspro.atlassian.net/browse/PP-1066).
For now, as a proof of verification I'll just post pbsnodes output as that would exercise the code.

**Comment by lisa-altair** [comment]
I agree that pbsnodes -av output will exercise the changed code and prove you haven't broken anything.  Works for me.

**Comment by lisa-altair** [comment]
The test results look good, and it exercises your changes.  Thanks @arungrover.  I sign off.

**Comment by bhroam** [comment]
I merged in the PR

**Comment by arungrover** [comment]
Thanks @bhroam

**Pull request merged**
