### PR TITLE
Intermittent failures in TestAdminSuspend.test_hook due to fewer attempts to match logs

### PR DESCRIPTION
**Pull request by latha-subramanian**
#### Bug/feature Description
Intermittent failures in test_hook of TestAdminSuspend due to fewer attempts to match logs

#### Affected Platform(s)
* All

#### Cause / Analysis / Design
The value of 'max_attempts'  argument to log_match was insufficient in some slower test bed machines. 

#### Solution Description
Let the test try and match logs with the default number of attempts (60). 

#### Testing logs/output
[afterfix_test_hook.txt](https://github.com/PBSPro/pbspro/files/2497623/afterfix_test_hook.txt)

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by latha-subramanian** [comment]
Thanks @bhroam , @lisa-altair . 
I have rebased. @PBSPro/pbspro-maintainers, Ready for merge . Please take it forward.

**Comment by bhroam** [comment]
Looks like your are out of date.  Please rebase again.

**Comment by latha-subramanian** [comment]
@bhroam , I have rebased again. Please take it forward.

**Comment by latha-subramanian** [comment]
@bhroam, The checks have passed after rebase. Please take it forward.

**Comment by bhroam** [comment]
I merged in the PR.

**Comment by latha-subramanian** [comment]
Thanks @bhroam

**Pull request merged**
