### PR TITLE
PP-902: PTL fails to parse mom config if more than one spaces are pre…

### PR DESCRIPTION
**Pull request by borlesanket**
#### Issue-ID

* **[PP-902](https://pbspro.atlassian.net/browse/PP-902)**

#### Problem description
* Parsing mom config file fails when there are more than one spaces on single line between attribute and its values

#### Cause / Analysis
* Inside mom parse_config split function fails to get key and value for the entry where the string is separated by more than one spaces on a single line.

#### Solution description
* Update split to consider the first space after the attribute name while splitting the line.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
@borlesanket I don't see any evidence of testing in the PP ticket.  Could you add it?

**Comment by borlesanket** [comment]
@hirenvadalia , I have updated the checklist.

@bhroam , I have attached the test execution to PP ticket by having fix locally, the test is cray specific which does mom parse config inside it.

**Comment by hirenvadalia** [comment]
@borlesanket Thanks. Checklist looks good now.

**Comment by bhroam** [comment]
I merged in the pull request.

**Pull request merged**
