### PR TITLE
PP-297: Update server dynamic resource smoke test case in PTL

### PR DESCRIPTION
**Pull request by saritakh**
#### Issue-ID

* PP-297

#### Problem description
* Update server dynamic resource smoke test case in PTL

#### Cause / Analysis
* Enhancement of server dynamic resource smoke test

#### Solution description
* Added test steps to create server dynamic resource, submit a job with its request and verify that the job runs along with the resource in its list

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added tests to cover my changes. To create automated tests, see **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**.
- [x] All new and existing automated tests have passed. See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**.
- [x] I have attached automated (PTL)/manual test logs to the associated Jira ticket.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by hirenvadalia** [comment]
@saritakh Changes look good to me. Please sign CLA so collaborators can merge your changes.

**Comment by subhasisb** [comment]
Sarita you would need another sign off.

**Comment by kjakkali** [comment]
Changes look good.  I sign off

**Comment by subhasisb** [comment]
@saritakh please add why the other checklist items like ptl and test cases are not required for your code fix

**Comment by saritakh** [comment]
@subhasisb 
 I have added tests to cover my changes. 
------ This code change is enhancement of a smoke test case
 All new and existing automated tests have passed. 
------ Continuous integration on travis has passed
 I have attached automated (PTL)/manual test logs to the associated Jira ticket.
------- Yes

**Comment by subhasisb** [comment]
@saritakh can you kindly rebase your code from base - its currently out of sync

**Comment by saritakh** [comment]
@subhasisb I have updated the code.

**Pull request merged**
