### PR TITLE
Kerberos support

### PR DESCRIPTION
**Pull request by vchlum**
#### Issue-ID

* **[PP-468](https://pbspro.atlassian.net/browse/PP-468)**

#### Problem description
* add kerberos support to pbspro

#### Cause / Analysis
* pbspro does not support kerberos

#### Solution description
* This solution come from a former colleague of mine. He already left our company. I will do futher possible changes.
* you need to install krb5-multidev libkrb5-26-heimdal packages
* for compilation with kerberos add to configure following option (or similar; tested on kerberos heimdal, debian):
--with-krbauth PATH_KRB5_CONFIG=/usr/bin/krb5-config.heimdal
* [documentation here](https://pbspro.atlassian.net/wiki/display/PD/PP-468+Kerberos+support)

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [x] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [x] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by subhasisb** [comment]
@vchlum Thanks for the PR. Travis found unsigned commits in the PR. Kindly sign your commits.

**Comment by subhasisb** [comment]
@vchlum This is obviously a large change and we will need several days to go over it. Meantime, are you creating specific tests (automated preferably) to test out this feature itself? If not, could you add a few manual tests to the Jira ticket, and attach test results as well?

**Comment by subhasisb** [comment]
@vchlum some instructions as to how to make this changes testable on CentOS will be great. We would love to test that kerberos now works on CentOS as well.

**Comment by vchlum** [comment]
Hello @subhasisb, as I was writing in the first post. This commit come from my former colleague. I have no success with compiling on centos yet. I also didn't realized that the implementation needs our own library [krb525](https://github.com/CESNET/krb525). Is it feasible to use it? It is used for renewing the tickets.

**Comment by vchlum** [comment]
On centos:
```
git clone https://github.com/CESNET/krb525.git
cd krb525
./autogen.sh
./configure --prefix=/usr
make && make install
```

`yum install heimdal-libs heimdal-devel` installed from [here](https://pkgs.org/search/heimdal)

finally:
```
cd pbspro
./autogen.sh
CFLAGS="-std=gnu99 -D_GNU_SOURCE -D__STDC_FORMAT_MACROS -D__TOLDGROUP -D__STDC_FORMAT_MACROS" CXXFLAGS="-std=c++0x -D_GNU_SOURCE -D__STDC_FORMAT_MACROS" ./configure --with-krbauth PATH_KRB5_CONFIG=/usr/lib/heimdal/bin/krb5-config --prefix=/opt/pbs
make && make install
```

**Comment by subhasisb** [comment]
@vchlum Compilation on CentOS is probably something others can help with. However, the implementation needing your own kerberos library is probably a bigger issue. The older implementation of Kerberos implementation used the MIT library. So could you help with changing the code to use a more generic library?

**Comment by vchlum** [comment]
@subhasisb I will look into it. Im not sure now. Change the implementation to use generic library would be pretty big change. It probably means to change the principle of this implementation, which would take some time. If there is no way to use our krb525 then maybe we can reject this commit for now...? I will try to come with proper solution later.

**Comment by subhasisb** [comment]
Thanks for reverting @vchlum. Per your suggestion I will close the pull request for now. Kindly feel free to get back whenever you get ready.

**Pull request closed without merging**
