### PR TITLE
pbs_snapshot fails to anonymize accounting records

### PR DESCRIPTION
**Pull request by agrawalravi90**
#### Bug/feature Description
* When capturing snapshot with --obfuscate, pbs_snapshot fails with the following error:
Traceback (most recent call last):
  File "pbs_snapshot.py", line 195, in <module>
  File "site-packages/ptl/utils/pbs_snaputils.py", line 1615, in capture_all
  File "site-packages/ptl/utils/pbs_snaputils.py", line 1269, in capture_server
  File "site-packages/ptl/utils/pbs_snaputils.py", line 1121, in __capture_acct_logs
  File "site-packages/ptl/utils/pbs_snaputils.py", line 889, in __capture_logs
  File "site-packages/ptl/utils/pbs_anonutils.py", line 1097, in anonymize_accounting_log
ValueError: need more than 1 value to unpack
Failed to execute script pbs_snapshot

#### Affected Platform(s)
* All Linux

#### Cause / Analysis / Design
* This happens when anonymizing an accounting record which is corrupt (instead of a key=value pair, it has only a single string)

#### Solution Description
* Making the code robust to such bad records so that they get skipped instead
* pbs_snapshot will also print out number of bad records found at the end
* pbs_snapshot -l DEBUG will print out the actual bad records which were found

#### Testing logs/output
* No good way to test this, I just removed the value from 'user' in 2 of the accounting records and took a snapshot with --obfuscate. Attaching snapshot logs here. pbs_snapshot.log is at default log level, at the end you'll see a log line printing the number of bad accounting records found. pbs_snapshot_debug.log was taken with log level set to DEBUG, if you search through it you'll find the log messages for bad accounting records that were found.
[pbs_snapshot_debug.log](https://github.com/PBSPro/pbspro/files/2308158/pbs_snapshot_debug.log)
[pbs_snapshot.log](https://github.com/PBSPro/pbspro/files/2308159/pbs_snapshot.log)

I also ran TestPBSSnapshot:
[testpbssnapshot.log](https://github.com/PBSPro/pbspro/files/2312037/testpbssnapshot.log)

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [X] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [X] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [X] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
Codacy found something that looks alarming.  If you click "view 13 issues", it will show you some for the file you modified.  The one marked red sounds like you are passing more arguments to a function than are declared.

**Comment by agrawalravi90** [comment]
Thanks Bhroam, the Codacy warnings were all in old code, some of it pre-dates me, I tried to fix as many of them as I could.

**Comment by agrawalravi90** [comment]
Thanks Bhroam. Requesting one more review please.

**Comment by agrawalravi90** [comment]
One more review please, thanks

**Comment by agrawalravi90** [comment]
Thank you Arun! I'll rebase

**Comment by arungrover** [comment]
Hey @agrawalravi90, It is again out of sync with master, can you please rebase again?

**Comment by agrawalravi90** [comment]
@PBSPro/pbspro-maintainers , rebasing this for the 3rd time now, please merge this before others, thanks.

**Comment by agrawalravi90** [comment]
thanks for the merge Arun!

**Pull request merged**
