### PR TITLE
PP-1119: Creating Reservations Uses Memory after Free

### PR DESCRIPTION
**Pull request by vstumpf**
#### Issue-ID

* **[PP-1119](https://pbspro.atlassian.net/browse/PP-1119)**

#### Problem description
* AddressSanitizer complains when creating a reservation

#### Cause / Analysis
* req_confirmresv frees the batch request before using it later. 

#### Solution description
* This was introduced in PP-1034, so I moved the accesses before the free.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by vstumpf** [comment]
Ok, I can change it @prakashcv13 .

If the malloc fails, the accounting log cannot be written. Should this prevent the reservation from being confirmed? In the previous iteration it didn't, so I'm going to keep that functionality here. If it should change, let me know.

**Comment by mike0042** [comment]
IMHO, failure to write an accounting record should prevent the reservation from being confirmed because the accounting log would be incomplete. It sounds like this is a change in behavior, so I suggest you post to the forum describing the change. I don't think a full design document is necessary since you'll be fixing something that is essentially broken to begin with. Once approved, this PR may move forward.

**Comment by vstumpf** [comment]
I've just totally removed the malloc call with a char array, circumventing the issue.

**Comment by vstumpf** [comment]
@prakashcv13, can you review this again when you get the chance?

Thanks

**Comment by vstumpf** [comment]
There is no ASAN output if it doesn't find an error.

**Comment by bhroam** [comment]
Still looks good.  I sign off again.  Please squash and rebase for the final merge.

**Comment by bhroam** [comment]
I merged in the PR.

**Comment by vstumpf** [comment]
@bhroam Thanks!

**Pull request merged**
