### PR TITLE
PP-785, PP-778: PTL should use same version as PBS & Bump up PBS version to 17

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Issue-ID

* **[PP-785](https://pbspro.atlassian.net/browse/PP-785)**
* **[PP-778](https://pbspro.atlassian.net/browse/PP-778)**

#### Problem description
* PP-785: PTL has different version than PBS
* PP-778: pbspro repo uses old version

#### Cause / Analysis
* PP-785: Currently PTL has its own versioning scheme but PTL is part of PBS so it should use same version as PBS
* PP-778: None

#### Solution description
* PP-785: Use same version as PBS for PTL
* PP-778: Bump up PBS version to 17.1.0

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by arungrover** [comment]
@hirenvadalia change looks good. I do have a small comment about documentation. With this change in place, PTL's quick start guide in confluence needs a change now. One can not install PTL anymore unless they have configured PBS.

**Comment by hirenvadalia** [comment]
Hey @arungrover Thanks for reminding to update document. I have update install instruction mentioning that user have to first configure PBS/PTL before installing PTL. Please have a look and let me know your view.

**Comment by arungrover** [comment]
looks good to me. I sign-off

**Comment by arungrover** [comment]
Please attach test logs in the respective tickets and rebase/squash for merge

**Comment by hirenvadalia** [comment]
@arungrover I have rebased branch with latest master. And regarding test log I don't think we need that as this is just a PTL version change + increment in PBS version which we can see in Travis log easily. If you want I can attach Travis log in tickets.

**Comment by arungrover** [comment]
@hirenvadalia  I agree you don't need any PTL here. At the very minimum just attach log of pbs and PTL printing the same version.

**Comment by hirenvadalia** [comment]
@arungrover Thanks. I have added snip from Travis logs which shows PTL and PBS version. Please have a look and let me know if it need more info.

**Pull request merged**
