### PR TITLE
Sometimes test case SmokeTest.test_fairshare_enhanced fails due to race condition

### PR DESCRIPTION
**Pull request by Bhagat-Rajput**
#### Bug/feature Description
* SmokeTest.test_fairshare_enhanced test case fails sometimes because of the race condition.
* Race condition occurs because fairshare usage file is not updated instantly.

#### Affected Platform(s)
* ALL

#### Cause / Analysis / Design
* Currently, after submission of one set of job we are not triggering the scheduling cycle hence the  fairshare usage does not get updated immediately.

#### Solution Description
* Need to trigger the scheduling cycle when job is in R state to update the fairshare usage instantly.

#### Testing logs/output
* Testing log:
[ptl_fairshare_enhanced.txt](https://github.com/PBSPro/pbspro/files/2210531/ptl_fairshare_enhanced.txt)

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by agrawalravi90** [comment]
"Sometimes test case SmokeTest.test_fairshare_enhanced fails" is a perfectly good title, please don't mention "nightly" here, it doesn't make sense for PBS open source.

**Comment by Bhagat-Rajput** [comment]
Thanks @agrawalravi90, I have renamed it.

**Comment by bhroam** [comment]
@Bhagat-Rajput just renaming the PR doesn't fully fix the problem.  You need to fix your commit title as well.  Do a git commit --amend -m "new message" and remove 'nightly'.  You'll need to force push after that.

**Comment by Bhagat-Rajput** [comment]
Thanks @bhroam, I have changed the commit message.

**Comment by Bhagat-Rajput** [comment]
Thanks @suresh-thelkar and @bhroam, rebased and ready to merge.

**Comment by bhroam** [comment]
Looks like something got merged ahead of you.  Please rebase again.

**Comment by Bhagat-Rajput** [comment]
Rebased

**Comment by Bhagat-Rajput** [comment]
Rebased!

**Comment by bhroam** [comment]
@Bhagat-Rajput sorry, but something got merged in ahead of you again.  Please rebase again.  After you do, consider asking @subhasisb to merge it for you.  If not, I'll try and merge it first thing tomorrow morning.

**Comment by Bhagat-Rajput** [comment]
It's ok @bhroam, rebased it again.Thanks

**Comment by bhroam** [comment]
Thanks!  I merged in the PR.

**Pull request merged**
