### PR TITLE
PP-983: mom crash due to memory leak on HUP

### PR DESCRIPTION
**Pull request by dilip-krishnan**
#### Issue-ID

* **[PP-983](https://pbspro.atlassian.net/browse/PP-983)**

#### Problem description
* Mom crashed due to memory leak on HUP.
#### Cause / Analysis
* With BASIL 1.3 and above, alps introduce "Socket" element in it's inventory xml response. While parsing  "Socket" element  one of the older existing element "Segment"  was effected, and in-case of a node with multiple socket, the segment element structure and all the substructure pointer within it were getting leaked.

#### Solution description
* To avoid the memory leak, "Segment" element needs a better design to fill the segment information while keeping it backward compatible.
#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [ ] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by arungrover** [comment]
@dilip-krishnan  I ran a static analysis tool and it reported following leak issues in alps.c (master branch):
[src/resmom/linux/alps.c:2629]: (error) Memory leak: label
[src/resmom/linux/alps.c:2761]: (error) Memory leak: accelerator
[src/resmom/linux/alps.c:2770]: (error) Memory leak: accelerator
[src/resmom/linux/alps.c:2909]: (error) Memory leak: accelalloc
[src/resmom/linux/alps.c:345]: (error) Common realloc mistake: 'requestBuffer' nulled but not freed upon failure

Please have a look, you may want to resolve these along with this ticket.

**Comment by dilip-krishnan** [comment]
Hi @arungrover , 
   I have made few changes based on the analysis report, can you tell me what static analysis tool you used, also if possible please run it on https://github.com/dilip-krishnan/pbspro/tree/PP-983 branch.

Regards
Dilip

**Comment by dilip-krishnan** [comment]
Hi @arungrover ,
     I have addressed your comments and attached the cppcheck results to the ticket. Please re-review the latest changes.

**Comment by arungrover** [comment]
@dilip-krishnan please rebase and squash

**Comment by dilip-krishnan** [comment]
Hi @arungrover ,
   I've squashed and rebased this PR, it's ready for merge now.

**Comment by arungrover** [comment]
I'm late in writing this comment on the pull now. I was hoping to request for a change in the test to make sure its implementation matches the test case name. @dilip-krishnan you may want to consider raising another pull to modify test.

**Pull request merged**
