### PR TITLE
PP-1071, PP-1072: Text gets jumbled and spills into borders in Windows installer graphic; win_postinstall message updates

### PR DESCRIPTION
**Pull request by bremanandjk**
#### Issue-ID: PP-1071: PP-1072

* **[PP-1071](https://pbspro.atlassian.net/browse/PP-1071)**

#### Problem description
* Text gets jumbled and spills into borders in Windows installer graphic
* Change needed in postintall python script.

#### Solution description
* Modified the Graphic image to fix this issue.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [x] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/spaces/PD/pages/53188191/PP-854+PBS+Pro+for+Windows+needs+an+installer)** for details.
- [x] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/spaces/PD/pages/53188191/PP-854+PBS+Pro+for+Windows+needs+an+installer)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
This pull request doesn't change the EDD.  Please rephrase your commit message to not mention the EDD updates.

**Comment by bremanandjk** [comment]
I somehow missed this notification for your review comment, sorry about that. 

Yes, I have modified EDD for this PR, Its here https://pbspro.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=53189458&selectedPageVersions=5&selectedPageVersions=4

Doesn't it make sense to mention EDD update at commit.? , Let me know your suggestion to mention or remove.

**Comment by bhroam** [comment]
@bremanandjk  The EDD is not part of that pull request.  There is an EDD associated with the code that is being changed as part of this request, but that is not uncommon.  The pull request/commit message should describe what is going into the repo.  The EDD is separate.

**Comment by bremanandjk** [comment]
@bhroam Thanks for your suggestion, I agree to that. 
I have updated the commit message and PR title, please share your further review comments/signoff.

**Comment by bhroam** [comment]
Looks good.  I sign off.

**Comment by bremanandjk** [comment]
Thanks for your approval @bhroam & @sid2364 
@PBSPro/pbspro-maintainers its ready to merge, please take further. Thanks

**Comment by hirenvadalia** [comment]
@bremanandjk I think you need to update PR title and commit message to have proper tickets ids. like ```PP-XXX, PP-YYY``` instead ```PP-XXX: PP-YYY:```

**Comment by bremanandjk** [comment]
@hirenvadalia , Do we have any specification for using the comma "," as the delimiter in case of multiple issue id? 
Anyway, I have modified here. I feel its good to specify the document section.

**Comment by subhasisb** [comment]
All looks good. Merging.

**Pull request merged**
