### PR TITLE
PP-622: PTL returns trancated Variable_List if it has newline

### PR DESCRIPTION
**Pull request by vishwaks**
#### Issue-ID

* **[PP-622](https://pbspro.atlassian.net/browse/PP-622)**

#### Problem description
* PTL returns truncated Variable_List if a variable has newline character

#### Cause / Analysis
* In PTL, the run_cmd function used splitlines() (delimiter is newline-\n) to split the output. So if any variable contains newline, its end up with truncated output of Variable_List.

#### Solution description
* Solution for this issue, is to use the correct delimiter for the status requests. So introduced new argument for the run_cmd method split_lines(default to True), and call it with split_lines=False when the call is for the status of JOB, QUEUE, SERVER and NODE, by that it will give string output without splitting and then split it accordingly(using delimiter newline with 4 spaces-\n    ).

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by vishwaks** [comment]
@PBSPro/pbspro-maintainers Please review this PR.

Thanks,

**Comment by arungrover** [comment]
@vishwaks  Does this change only apply to ptl when it is using CLI mode? Does it needs changes in API mode too?

What happens when I export an environment variable with a newline followed by 4 spaces in it? What if it is exported with 2 newline characters in it?

I think we should address this problem differently. Variable_List is a comma separated key-value pair and we should probably try to parse it till we get no comma between two consecutive key-value pair.

**Comment by vishwaks** [comment]
@arungrover Thanks for comments. Yes it is only for CLI mode.

I was checking other points also and I found that we can set environment variables in a same format like PBS commands results(I mean output of qstat -f), Below is my observation

[root@node1 qsub]# export A="b = c
    d = e
    g = h
     t = u"

And qstat -f output looks like:

    substate = 42
    Variable_List = PBS_O_HOME=/root,PBS_O_LANG=en_US.UTF-8,PBS_O_LOGNAME=root,
        PBS_O_PATH=/opt/pbs/default/bin/:/opt/pbs/default/bin/:/sbin:/bin:/usr
        /sbin:/usr/bin:/opt/pbs/default/bin:/opt/pbs/default/sbin,
        PBS_O_MAIL=/var/spool/mail/vishwak,PBS_O_SHELL=/bin/bash,
        PBS_O_WORKDIR=/tmp/ptl_src/tests/dejagnu/testsuites/qsub,
        PBS_O_SYSTEM=Linux,A=b = c
    d = e
    g = h
    t = u,
        MANPATH=:/opt/pbs/default/share/man,HOSTNAME=node1,SHELL=/bin/bash,
        TERM=xterm,HISTSIZE=1000,
        PERL5LIB=/home/vishwak/AUTO/lib/perl5/site_perl:/home/vishwak/AUTO/lib
        /site_perl:/home/vishwak/AUTO/share/perl5,OLDPWD=/tmp,USER=root,
        LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=4
        0;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;
        41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01
        ;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=
        01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*
        .bz2=01;31:*.tbz=01;31:*.tbz2=01;31:*.bz=01;31:*.tz=01;31:*.deb=01;31:*
        .rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31
        :*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35
        :*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;3
        5:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=0
        1;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv
        =01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.q
        t=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.f
        lc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xc
        f=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.a
        nx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.
        mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:
        *.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36
        :,SUDO_USER=vishwak,SUDO_UID=500,USERNAME=root,
        PATH=/opt/pbs/default/bin/:/opt/pbs/default/bin/:/sbin:/bin:/usr/sbin:
        /usr/bin:/opt/pbs/default/bin:/opt/pbs/default/sbin,
        MAIL=/var/spool/mail/vishwak,
        PWD=/tmp/ptl_src/tests/dejagnu/testsuites/qsub,LANG=en_US.UTF-8,
        SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass,SHLVL=1,
        SUDO_COMMAND=/bin/su,HOME=/root,LOGNAME=root,
        PYTHONPATH=/tmp/PTL/lib/python2.6/site-packages:/home/vishwak/PTL/lib,
        PBS_CONF_FILE=/etc/pbs.conf,LESSOPEN=||/usr/bin/lesspipe.sh %s,
        SUDO_GID=500,G_BROKEN_FILENAMES=1,_=/opt/pbs/default/bin/qsub,
        PBS_O_QUEUE=fast,PBS_O_HOST=node1
    euser = root
    egroup = root
    hashname = 442.node1
    queue_rank = 431
    queue_type = E
    comment = Job run at Mon Feb 06 at 20:29 on (node1:mem=10240kb:ncpus=1)
    etime = Mon Feb  6 20:29:00 2017
    run_count = 1
    Submit_arguments = -V -- /bin/sleep 100
    executable = /bin/sleep
    argument_list = <jsdl-hpcpa:Argument>100</jsdl-hpcpa:Argument>
    project = _pbs_project_default
    run_version = 1

In this case, parsing till no comma between consecutive pairs, won't work. So need to look for different way of addressing this issue.

Thanks,

**Comment by arungrover** [comment]
@vishwaks in the case you mentioned A is the key and everything after first "=" is a value unless you hit a non-escaped ','
If we go by this approach we can still parse it in key value pairs.

**Comment by vishwaks** [comment]
Still we may hit an issue, if this environment variable appears last in the Variable_List. correct ?

**Comment by arungrover** [comment]
I assume that you get these env variables in a dict where key is attribute name "Variable_List" and value is the comma separated list as a string. Now while parsing if you do not hit a comma and your string ends then that is also an indicator that it was your last key-value pair.

**Comment by bhroam** [comment]
What is the status of this PR?  There has been no activity in nearly a month.

**Comment by vishwaks** [comment]
we are approaching different solution, So as of now I'm closing it. will re-open it once ready.

**Pull request closed without merging**
