### PR TITLE
Partial cherry pick of PR 759 for ical3

### PR DESCRIPTION
**Pull request by mike0042**
#### Bug/feature Description
* PBS Pro build fails on CentOS 7.6 because it uses ical3 where icaltime_from_timet() is deprecated
* This has already been fixed in master with PR #759 
* Performed a partial cherry pick from PR #759 
* This was identified when OpenHPC add CentOS 7.6 to their builds

#### Affected Platform(s)
* CentOS 7.6

#### Cause / Analysis / Design
* icaltime_from_timet() is deprecated, don't use it

#### Solution Description
* Replace instances of icaltime_from_timet() with icaltime_from_timet_with_zone()

#### Testing logs/output
* [ptl.log](https://github.com/PBSPro/pbspro/files/2649501/ptl.log)

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [X] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [X] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by mike0042** [comment]
I'm going to squash these commits. Nobody needs to see multiple attempts at making OpenSUSE work for TravisCI. The original commit affected the one C file in this PR and hasn't changed. The rest were for TravisCI. Please note I had to disable -Werror for the OpenSUSE build because this branch doesn't have all of the warnings fixed like master.

**Comment by mike0042** [comment]
FYI... the changes to Travis were necessary because the old OpenSUSE repo URL is gone. It appears to have been updated earlier today. We were forced to transition to Leap as we do for master.

**Comment by mike0042** [comment]
Could you please merge this change and tag it as 18.1.4 @subhasis?

**Comment by mike0042** [comment]
Please have a look at this when you get the chance @subhasisb.

**Comment by mike0042** [comment]
If we do release 18.1.4 this PR should be included. Closing for now since the OpenHPC folks have created a patch for the same changes.

**Comment by mike0042** [comment]
There has been a request on the forum for this change to be merged into the release_18_1_branch:
http://community.pbspro.org/t/pbspro-build-failure-on-centos7-with-branch-release-18-1-branch/1358

**Comment by guillaumeeb** [comment]
I confirm this is interesting to me, thanks @mike0042!

**Comment by mike0042** [comment]
@PBSPro/pbspro-maintainers please take this forward.

**Pull request merged**
