### PR TITLE
PP-345: cpuset_destroy_delay ignores child processes

### PR DESCRIPTION
**Pull request by mike0042**
#### Issue-ID

* PP-345

#### Problem description
* cpuset mom does not kill child processes once it starts waiting cpuset_destroy_delay seconds

#### Cause / Analysis
* Mom was not re-polling the PIDs in the target cpuset allowing child processes to survive

#### Solution description
* Re-poll the PIDs of the target cpuset every time, prior to sending them SIGKILL. Note that this change only affects builds where --enable-cpuset is specified. This change is being merged from 13.1.1.

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [x] I have added tests to cover my changes. To create automated tests, see **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**.
- [X] All new and existing automated tests have passed. See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**.
- [X] I have attached automated (PTL)/manual test logs to the associated Jira ticket.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by subhasisb** [comment]
@mike0042 looks like a smoke test failed. You might have to either adjust the test or update the code to satisfy the test. 

In the checklist, if you remove the extra spaces around the square braces[], then they will appear as tick boxes on the final display.

**Comment by bhroam** [comment]
The changes look good.  I sign off.

**Comment by bayucan** [comment]
The changes looked fine. I sign off. It's odd why the smoketest failed. The code change should affect only cpuset moms.

**Comment by mike0042** [comment]
I agree with you @bayucan. I can't explain why the test failed. I updated my branch without making any changes to the fix and all the tests passed this time. One of the smoketests may not be running reliably.

**Comment by mike0042** [comment]
I filed PP-359 for the issue with test_round_robin.
https://pbspro.atlassian.net/browse/PP-359

**Comment by subhasisb** [comment]
@mike0042 are you planning to submit ptl tests for this soon? If you think u cant have PTL tests, please add an explanation for the same in the comments. (in which case you need to add some manual tests) 

Also you need to attach some evidence of testing as in either case (whether you have manual or automated tests) - The current Travis test logs probably dont test the cpuset functionality, so those are not good enough

**Comment by mike0042** [comment]
Travis-ci was not triggered. Closing and reopening pull request.

**Comment by subhasisb** [comment]
Code looks good and all checks have passed. Merging.

**Pull request merged**
