### PR TITLE
PP-227: Increase displayed license count

### PR DESCRIPTION
**Pull request by sid2364**
#### Issue-ID

[PP-227](https://pbspro.atlassian.net/browse/PP-227)

#### Problem description

Increase displayed license count
#### Cause / Analysis

Available licenses were only 1,000,000.
#### Solution description

Increased floating licenses to 10,000,000
#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [x] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [x] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) _(or)_
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

****_For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).**_**

### CODE REVIEW

**Comment by bhroam** [comment]
The code looks fine, but I the title says you're going to be removing a comment.  I don't see any comments being removed.

**Comment by sid2364** [comment]
This was the title of the issue that was reported in May. The comment must have been removed since.

Maybe I should have not used the original title of the issue while posting it here?

**Comment by bhroam** [comment]
If the comment was removed outside of this ticket, then why don't you update both the ticket and pull request's title.

**Comment by sid2364** [comment]
Updated the titles of both the ticket and the pull request.

**Comment by arungrover** [comment]
Question: as part of this pull request, isn't there a need to update sockets count in license_client.c also?

**Comment by sid2364** [comment]
This was the initial title of the issue that was reported a couple of
months ago. I suppose the comment had since been removed.

Maybe I shouldn't have put the original title of the issue?

**Comment by sid2364** [comment]
As far as I understand, the socket count in license_c.c specifies the number of available licenses for hardware, and the license count in checkkey.c the number of jobs that can be run with the license. 
There would be a need to scale that up too. But I'm not sure, maybe someone can confirm this?

@subhasisb Should we be increasing the number of socket licenses too?

**Comment by sid2364** [comment]
I have made changes in license_client.c, increasing the socket count there.

But  _int sockets_consume(int)_, has deprecated. This was the function used to update the value of the socket count. The function _void allocate_cpu_licenses(job*)_ in checkkey.c simply assigns 1 to licenses allocated, i.e. there is no decrease of licenses anywhere.

**Comment by arungrover** [comment]
@sid2364 looks good. Please rebase your branch and squash your commits.

**Comment by sid2364** [comment]
Rebased and squashed. Hope everything is fine.

**Pull request merged**
