### PR TITLE
PP-521: pbs_only_small_files_over_tpp.py script may fail in some cases

### PR DESCRIPTION
**Pull request by prakashcv13**
#### Issue-ID

* **[PP-521](https://pbspro.atlassian.net/browse/PP-521)**

#### Problem description
* PTL test case written for testing that only small files (size < 2MB) are sent over TPP does not pass on slower machines.

#### Cause / Analysis
* On slower machines it took more than 45 seconds to transfer the files from MoM host to server host. 

#### Solution description
* Use the job_requeue_timeout attribute and set the timeout to a higher value.
* Made changes so that the test is not dependent on the order in which moms are provided in -p moms.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [x] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

…st pass on slow machines.

### CODE REVIEW

**Comment by dilip-krishnan** [comment]
Hi Prakash,
    Changes look good. I sign-off.

**Comment by arungrover** [comment]
@prakashcv13 change looks good to me.
Please attach test results/logs to the ticket and rebase it with master.

**Comment by prakashcv13** [comment]
Done!

**Comment by arungrover** [comment]
merging it in

**Pull request merged**
