### PR TITLE
PP-909: Update make-ug of PTL to allow test execution as a non root user

### PR DESCRIPTION
**Pull request by borlesanket**
#### Issue-ID

* **[PP-909](https://pbspro.atlassian.net/browse/PP-909)**

#### Problem description
* make-ug fails to create user home directories with 755 permission

#### Cause / Analysis
* System default umask does not allow to create user home directories with 755 permission

#### Solution description
* To specify UMASK parameter as '0022' while constructing useradd command.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by borlesanket** [comment]
@agrawalravi90 , I have attached the simple job submission test of a SmokeTest to jira ticket.

**Comment by agrawalravi90** [comment]
Thanks, looks good to me.

**Comment by agrawalravi90** [comment]
You need one more reviewer before this can be merged in.

**Comment by agrawalravi90** [comment]
Hey guys,

This is literally a single line change, shouldn't take long to review :) requesting a 2nd reviewer. Thanks!

**Comment by agrawalravi90** [comment]
Thanks Brem!
@borlesanket , please rebase your branch in preparation for merge.

**Comment by borlesanket** [comment]
@agrawalravi90 , me, Kumar and Hiren had a discussion on this issue. So still there is a confusion  whether to do this change or revert the change done in os.chdir (back to /tmp location) for normal linux and keeping that change only for Cray and discard this pull request. Kumar will raising this issue to steering committee so maybe by Tuesday EOD will conclude something on this.

**Comment by agrawalravi90** [comment]
Sanket, I couldn't find the document, could you please post the link to it?

**Comment by agrawalravi90** [comment]
Ah, I mistakenly thought that there was an EDD for this ticket. The doc change looks fine to me. Thanks!

**Comment by agrawalravi90** [comment]
Thanks,I just merged it in

**Pull request merged**
