### PR TITLE
pbs_init_script test is failing due to sudo issues on some systems

### PR DESCRIPTION
**Pull request by anamikau**
#### Bug/feature Description
* *Bugs: Test was failing when run as non-root users. Also leaving the system in unusable state*

#### Affected Platform(s)
* *Platform (ALL)*

#### Cause / Analysis / Design

* *Bugs: test was running script as sudo instead of the init command*

#### Solution Description
* *updated run command to run as sudo. Also added tearDown as next test would fail since server and schedule are not running*

#### Testing logs/output
* *Please attach your test log output from running the test you added (or from existing tests that cover your changes)
[pbs_init.txt](https://github.com/PBSPro/pbspro/files/2203216/pbs_init.txt)

*

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by agrawalravi90** [comment]
Hey Anamika, please change the title of the PR and the commit to reflect the actual bug that's being fixed. Right now it reflects the solution to the bug instead.

**Comment by anamikau** [comment]
Thanks @ashwathraop for the sign off. There was a codify error that I have addressed. Kindly re-review.

**Comment by anamikau** [comment]
Thanks @ashwathraop and @bhroam. I have rebased and squashed. Please take this PR forward.

**Comment by bhroam** [comment]
I merged in the PR.

**Pull request merged**
