### PR TITLE
PP-309: fix for strict_ordering not working

### PR DESCRIPTION
**Pull request by arungrover**
#### Issue-ID

PP-309

#### Problem description
Problem with strict_ordering, jobs running when they shouldn't have

#### Cause / Analysis
Problem is that we deprecated "backfill"option from sched_config and used it as true by default. Now even when we set backfill_depth to 0 it is still considered as backfill true and never stops running jobs because of strict ordering.

#### Solution description
consider backfilling as false when backfill_depth is set to 0

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [x] I have added tests to cover my changes. To create automated tests, see **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**.
- [x] All new and existing automated tests have passed. See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**.
- [x] I have attached automated (PTL)/manual test logs to the associated Jira ticket.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
Looks good to me.  I sign off.

**Comment by suresh-thelkar** [comment]
Code changes look good to me. I sign off.

**Comment by arungrover** [comment]
ptl script's filename and test case name wasn't appropriate. I've changed it now. I need one sign-off on this specific change.

**Comment by suresh-thelkar** [comment]
change looks good to me. I sign off.

**Pull request merged**
