### PR TITLE
PP-867: Add a note to sched_config : mom_resources being deprecated

### PR DESCRIPTION
**Pull request by dinesh1306**
#### Issue-ID

* **[PP-867](https://pbspro.atlassian.net/browse/PP-867)**

#### Problem Description
* mom_resources is deprecated, need a note in scheduler  config file

#### Solution description
* Added a note in scheduler config file "The mom_resources option is deprecated and will likely go away in a future release. Use exechost_periodic hook to set the resource values"

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

.

### CODE REVIEW

**Comment by mike0042** [comment]
@dinesh1306 Please add an explanation to the JIRA ticket as to why testing is not required due to the fact you are only changing a comment, then check the appropriate item in the checklist. Maintainers aren't allowed to merge pull requests until they conform to policy.

**Comment by dinesh1306** [comment]
I comment on JIRA ticket why testing is not required.

**Comment by mike0042** [comment]
Thank you for updating the ticket. I checked the box pertaining to testing in the PR description. Please rebase your dev branch in preparation for merge.

**Comment by dinesh1306** [comment]
branch is rebased. ready for merge.

**Comment by mike0042** [comment]
Did you push your changes? It still looks like it needs a rebase.

**Comment by dinesh1306** [comment]
i rebased branch. ready for merge.

**Pull request merged**
