### PR TITLE
PP-294: Update pull request template to show checklist

### PR DESCRIPTION
**Pull request by subhasisb**
#### Issue
* PP-294

#### Problem
* pull request template does not show a checklist of artifacts of actions to the contributor

#### Cause
* No checklist added to pull request

#### Solution
* Added a checklist to the pull request template

### CODE REVIEW

**Comment by subhasisb** [comment]
The new pull request template will show as follows:



#### Issue-ID


* PP-XXXX

#### Problem description
* Describe the issue being fixed

#### Cause / Analysis
* Briefly describe root cause/analysis of the problem

#### Solution description
* Please describe your changes in detail for reviewers

#### Checklist:



- [ ] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [ ] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [ ] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added tests to cover my changes. To create automated tests, see **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**.
- [ ] All new and existing automated tests have passed. See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**.
- [ ] I have attached automated (PTL)/manual test logs to the associated Jira ticket.

**Comment by agrawalravi90** [comment]
The checklist looks really good Subhasis! Just a thought, it might be nice to add a link to the development guide here. For people who are seeing the template for the first time and have questions, it might be helpful to have a link right there.

**Comment by crjayadev** [comment]
This looks very good. The questions has links within, for reference, which is very good.

Notes on what is to be done after the pull request is merged could be added as a note towards the end. 
eg.
Note : When your code is merged you need to resolve the Jira ticket, update the fix information and the pull request link on Jira (https://pbspro.atlassian.net).

**Comment by subhasisb** [comment]
@agrawalravi90 added the link to the developers guide home at the bottom
@crjayadev , this will actually be shown while raising the pull request, so adding what to do after a merge is complete could be confusing here

**Comment by crjayadev** [comment]
Looks good.

**Comment by agrawalravi90** [comment]
Thanks Subhasis, I sign-off ..

**Pull request merged**
