### PR TITLE
PP-638: Online manual page updates

### PR DESCRIPTION
**Pull request by mike0042**
#### Issue-ID

* **[PP-638](https://pbspro.atlassian.net/browse/PP-638)**

#### Problem description
* Online manual pages require updates

#### Cause / Analysis
* Command parameter changes and deprecation of some features

#### Solution description
* Apply updates to online manual pages and build tools

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [X] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [X] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by crjayadev** [comment]
pbs-probe is planned to be deprecated ( https://pbspro.atlassian.net/browse/PP-474 ). Instead of fixing it, the file can be removed.

**Comment by agurban** [comment]
Hi Jayadev,

Deprecation happens before removal.  First we deprecate something,
then we wait a certain number of releases before removing it.

When was pbs-probe deprecated?  Thank you.

Regards,
-Anne

**Comment by bhroam** [comment]
Mike,
I don't have a problem with the man page changes.  I notice a C file is also in your fix.  Is it to fix that warning that snuck in some time ago?  Even if it is just to fix a warning, I don't think it should be together with a man page only fix.

**Comment by crjayadev** [comment]
Hi Anne,

You are right. We need to follow the due process for depreciation. We should handle PP-474 separately.

Warm Regards,

Jayadev C R

**Comment by mike0042** [comment]
@bhroam @arungrover Rebased and ready for merge.

**Comment by bhroam** [comment]
Everything looks good.  I merged in the request.

**Comment by pbsproci** [comment]
Hi Anne, Jayadev,

Pbs_probe was non-functional on the OSS side from the start. The plan was to remove it eventually. In that sense it was deprecated from the last release itself, ie, 14.1.

Regards,
Subhasis

**Pull request merged**
