### PR TITLE
OSS PBS failed to start daemons on postgres upgrade externally

### PR DESCRIPTION
**Pull request by Klovely**
#### Bug/feature Description
* *OSS PBS failed to start daemons on postgres upgrade externally*
     This is a cherry-pick from 18.1 branch [PR-708](https://github.com/PBSPro/pbspro/pull/708)    
- If postgresql is upgraded and PBS database is not upgraded, PBS dataservice fails to start.
- To reproduce the issue, upgrade postgresql and restart PBS.

#### Testing logs/output

-  Testing logs attached as  below
[after_fix_test_log.txt](https://github.com/PBSPro/pbspro/files/2571825/after_fix_test_log.txt)
[before_fix_test_log.txt](https://github.com/PBSPro/pbspro/files/2571826/before_fix_test_log.txt)

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by Klovely** [comment]
Thanks Anamika for review.
I updated title of the PR .

**Comment by Klovely** [comment]
@PBSPro/pbspro-maintainers , I have got one approval, please take the review of this PR.

**Comment by Klovely** [comment]
Thank you @riyazhakki and @agrawalravi90  , for the review and approval.
I have now rebased my branch please take it forward.

**Comment by agrawalravi90** [comment]
Please sign your commit, merging is blocked until you sign it, thanks

**Pull request merged**
