### PR TITLE
PP-484:PP-485: Tests for qstat dsv and json output

### PR DESCRIPTION
**Pull request by visheshh**
PP-484:PP-485:Tests for qstat dsv and json output
PTL tests for qstat -f -F json and qstat -f -F dsv 

#### Issue-ID

* **[PP-484](https://pbspro.atlassian.net/browse/PP-484)**
* **[PP-485](https://pbspro.atlassian.net/browse/PP-485)**

#### Problem description
*  Test cases required for testing qstat dsv and json output
#### Solution description
* Added test cases for qstat -f -F json , qstat -f -F dsv , qstat -f -F dsv -D<delimiter>, qstat -Bf -F json , qstat -Bf -F dsv , qstat -Bf -F dsv -D<delimiter>, qstat -Qf -F json , qstat -Qf -F dsv , qstat -Qf -F dsv -D<delimiter>

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [ ] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [x] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
Travis is failing due to pep8 non-compliance.  Please run your PTL test through pep8 and fix the warnings to get Travis to pass.

**Comment by bhroam** [comment]
Due to lack of activity, I'm closing this pull request.  @visheshh please reopen it when you are ready

**Comment by visheshh** [comment]
Hi Bhroam , 
Can you reopen the pull request . 
The feature was not merged yet , So Travis could not run that time . I have fixed the pep8 issues and updated the branch now. 
Thanks

**Comment by bhroam** [comment]
@visheshh Github isn't letting to reopen the request either.  It's telling me the branch has been either recreated or force-pushed.  I've requested @subhasisb to try.  He's the owner of the repo and may be able to do it.

**Comment by mike0042** [comment]
This might help: https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c

**Comment by agrawalravi90** [comment]
@visheshh why not just create a new PR? There were 0 review cycles on this PR so I don't think you even need to mention this PR in the new one.

**Comment by visheshh** [comment]
@bhroam @agrawalravi90 I will open a new pull request .

**Pull request closed without merging**
