### PR TITLE
PP-923: qrun failing if job's formula value is below threshold

### PR DESCRIPTION
**Pull request by bhroam**
#### Issue-ID

* **[PP-923](https://pbspro.atlassian.net/browse/PP-923)**

#### Problem description
* qrun fails on job which is under the job_sort_formula_threshold

#### Cause / Analysis
* When fairshare was added to the formula, the location of where the threshold was checked was moved into init_scheduling_cycle().  It used to be checked in query_jobs().  If a job was under the threshold, it was marked can_not_run so we wouldn't look at it again.  After the universe is queried, we unmark the qrun job as can_not_run so it will be considered to run.  The call to init_scheduling_cycle() was after we'd unmark the qrun job.

#### Solution description
* Move the call to init_scheduling_cycle() before we unmark the qrun job.

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [X] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [X] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [X] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
OK, @anamikau, I modified the test so that one of the job's formula value is 6 and I run that.  This is strictly under the threshold of 7.  It really shouldn't matter since while it says "under", it means <= threshold.

**Comment by arungrover** [comment]
please squash and rebase

**Comment by bhroam** [comment]
Thanks for the review @arungrover, @anamikau only looked at the test.  I still need one more reviewer.

**Comment by altair4** [comment]
@bhroam, @agurban :  I wish I didn't have to ask, but I think I do:  does PBS documentation have a formal definition for _under_?  That is, do we tell our readers whether it means _less than or equal to_ or _less than_?

**Comment by agurban** [comment]
We say, in AG 4.8.21, p. AG-135, "You can set a job priority threshold 
so that jobs with priority at or below the specified value do not run."

**Comment by bhroam** [comment]
@altair4 do you have any further comments?

**Comment by altair4** [comment]
Yes, @bhroam, sadly I do:  I have so far not found the place(s) that instantiate the rule that @agurban quoted from the AG (above).  I was looking on this as an excuse to refamiliarize myself with some of the  current scheduler code but it's proving to be more time-consuming than i thought, so I'd like to buy a clue.

**Comment by bhroam** [comment]
The code which checks the threshold is near the bottom of init_scheduling_cycle().

**Comment by altair4** [comment]
Got it - thanks for the directions.  The change looks fine to me.

**Comment by bhroam** [comment]
Thanks @altair4.  I've squashed and rebased for the merge.

**Pull request merged**
