### PR TITLE
PP-324: Add fairshare enhancement test case to PTL smoke test suite

### PR DESCRIPTION
**Pull request by saritakh**
#### Issue-ID

* PP-324

#### Problem description
* Added a fairshare enhancement test case to PTL smoke test suite

#### Cause / Analysis
* This new fairshare test case is to verify the use of math module in fairshare

#### Solution description
* Added test case "test_fairshare_enhanced" to PTL test suite SmokeTest 

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added tests to cover my changes. To create automated tests, see **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**.
- [x] All new and existing automated tests have passed. See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**.
- [x] I have attached automated (PTL)/manual test logs to the associated Jira ticket.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by arungrover** [comment]
Change looks good Sarita!
I sign-off.

**Comment by kjakkali** [comment]
Changes look good. I sign off.

**Comment by saritakh** [comment]
This change is ready to be merged. Request to please merge the same.

**Comment by subhasisb** [comment]
All good. Merging

**Pull request merged**
