### PR TITLE
PP-722: PTL post data analysis option max-postdata-threshold is not working as expected

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Issue-ID

* **[PP-722](https://pbspro.atlassian.net/browse/PP-722)**

#### Problem description
* While saving post analysis data PTL saves given max threshold + 1 for max post data

#### Cause / Analysis
* due to wrong if condition PTL saves given max threshold + 1 for max post data

#### Solution description
* corrected if condition

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by saritakh** [comment]
Change looks good to me.

**Comment by arungrover** [comment]
@hirenvadalia change looks okay.
I do not see any test logs where max-postdata-threshold or even post-analysis-data is getting used.
Please update the correct test results

**Comment by bhroam** [comment]
What is the status of this PR?  It looks like it was almost done, but stalled out.  It's been lingering for quite some time.

**Comment by hirenvadalia** [comment]
@arungrover I have added pre and post fix test results in ticket and also update branch with current master. Please have a look and let me know if anything is missing.

**Comment by arungrover** [comment]
All looks good. @hirenvadalia please add a fix version to the ticket.

**Pull request merged**
