### PR TITLE
PP-402: remove netlibtoc.lib liblmx-altair.lib dependency from the windows project files

### PR DESCRIPTION
**Pull request by lcnja**
#### Issue-ID

* **[PP-402](https://pbspro.atlassian.net/browse/PP-402)**

#### Problem description
* Error 319 fatal error LNK1181: can not open input file "netlibtoc.lib" "liblmx-altair.lib"

#### Cause / Analysis
* Incorrect Dependencies

#### Solution description
* Kindly remove Incorrect Dependencies from the windows project files.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [x] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [x] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

…ndows project files

### CODE REVIEW

**Comment by gajendrasharmagit** [comment]
As specified earlier please start the documentation here(https://pbspro.atlassian.net/wiki/display/PD) for removal of pbs_migration_asistant.bat. Steps to do migration upgrade on Windows, will change.

**Comment by gajendrasharmagit** [comment]
Please go through Section 7.10: Upgrading under Windows of PBS Installation guide:
http://www.pbsworks.com/pdfs/PBSProInstallGuide13.1.pdf
This document needs to be updated to address removal of pbs_migration_assistant.bat.

**Comment by gajendrasharmagit** [comment]
Please start a documentation on "Steps to do migration upgrade on Windows". Refer the Install guide section 7.10. Remove the reference to pbs_migration_asistant.bat. if the script is using a single command to set up a system wide environment variable, this will need to be run manually after removal of pbs_migration_asistant.bat. Let me know for any other help u need.

**Comment by gajendrasharmagit** [comment]
Since this issue is blocking the build of PBS Pro on Windows, I think it is best that we create a separate bug for documentation towards removal of pbs_migration_assistant.bat and let this code in.  I sign-off on the code changes.

**Comment by subhasisb** [comment]
I sign off on the code. 
The CI tests have passed, though we dont cover windows builds via that anyway.
We will complete the documentation in a separate bug.

**Pull request merged**
