### PR TITLE
Add the -b option to the PTL test's aprun invocation

### PR DESCRIPTION
**Pull request by lisa-altair**
#### Bug/feature Description
Make the aprun more agnostic within the PTL default job and the existing PTL tests using aprun, by adding the -b option when aprun is invoked.  See the aprun man page for more details.  

#### Affected Platform(s)
Platform: Cray X* series

#### Testing logs/output
[sim_smoke_output.txt](https://github.com/PBSPro/pbspro/files/2033437/sim_smoke_output.txt)

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [X] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by agrawalravi90** [comment]
Lisa, could you please mention the motivation behind this change? The man page for aprun (http://srinathv.github.io/blog/html/_downloads/aprun.txt) says the following about the -b option:
Bypasses the transfer of the application executable to
               compute nodes. By default, the executable is transferred to
               the compute nodes as part of the aprun process of launching
               an application. You would likely use the -b option only if
               the executable to be launched was part of a file system
               accessible from the compute node

I'm not sure I understand how this option would make aprun more agnostic. Actually, what do you mean by agnostic? Agnostic to what?

**Comment by lisa-altair** [comment]
@agrawalravi90, It's to make the job script more platform agnostic in the PBS PTL testing.  Both for the default job script, as well as within specific PTL tests that call aprun directly.  In the places I am changing it is a simple sleep job, and the test should use the sleep command local to where the job runs.
I'll update the title and description to make it clear this is a PTL only change, not a change to PBS.

**Comment by vccardenas** [comment]
@lisa-altair , the changes look good to me.

**Comment by lisa-altair** [comment]
@arungrover I have attached the smoktest output.

**Comment by arungrover** [comment]
Please rebase the branch Lisa

**Pull request merged**
