### PR TITLE
PP-1068: race condition in test_alter_standing_resv_start_time_before_run

### PR DESCRIPTION
**Pull request by npadole20**
**Issue ID:**
* [PP-1068](https://pbspro.atlassian.net/browse/PP-1068)

#### Affected Platform(s) and PBS Version
* Platform: All
* Bugs: 18.1.1

#### Cause / Analysis / Design
*  Race condition in "test_alter_standing_resv_start_time_before_run" test as the ralter command was executed with start time past the current time

#### Solution Description
* Changed the offset to ensure that reservation is submitted with such a start time so that there is enough time to perform the multiple ralter operations in the test case before the actual start time arrive 

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by npadole20** [comment]
@anamikau @mike0042 thank you for the review.
@agrawalravi90 we can implement what you are suggesting by reducing the shift for the last ralter. How about that? I don't want to keep the offset too high because it will take that much longer for the reservation to start.

**Comment by agrawalravi90** [comment]
I think I couldn't explain properly. From what I understand, and please correct me if I'm wrong, the old test was doing the following:
1) submitting a reservation that's going to start @ now + 20 seconds
2) ralter to change start to <old value> + 15 seconds
3) ralter to change start to <old value> - 15 seconds
4) ralter to change start to <old value> - 15 seconds
5) Then, it waits for the reservation to start

So, effectively, the test had 5 seconds to do steps 1) to 3), and if the machine took longer than that then it ended up in the race condition in step 4)

Your fix will increase the time that the test has to 15 seconds instead, which is definitely better, but I see 2 drawbacks:
1) The test is now 10 seconds slower to execute. Steps 1) to 3) might only take 2 seconds on a fast machine, but the test will nonetheless wait for 15 seconds.
2) Very unlikely, but what if it takes more than 15 seconds on a slow machine that's having a really bad day? The race condition will prevail.

So, this is what I am proposing:
1) Submit a reservation that's going to start @ **now + 300 (or some other crazy high number) seconds**
2) ralter to change start to <old value> + 15 seconds
3) ralter to change start to <old value> - 15 seconds
4) ralter to change start to **now + 5 seconds**
5) Then, wait for the reservation to start

Now, the test will effectively have 300 seconds before reaching step 4) where it changes the reservation's start to now + 5 seconds, which means that the test won't have to wait more than 5 seconds for the reservation to start.

I hope I'm making sense.

**Comment by npadole20** [comment]
@agrawalravi90 we have to wait for the first occurrence of the reservation to finish to verify that the start and end time of the second occurrence is unchanged. If we submit the reservation with an offset of 300, the end time will be (300 + duration). We will have to wait for almost (300 + duration) seconds before we can verify if the start and end time of the second occurrence is unchanged. It will increase the overall time of the test case.

**Comment by npadole20** [comment]
@agrawalravi90 in the next step we have specified "# Wait for the reservation occurrence to finish." 
So the sequence is -
1. # Wait for the reservation to start running.
2. # Wait for the reservation occurrence to finish.
3. # Check that duration of the second occurrence is not altered.

Thank you for the review and sign off.

**Comment by npadole20** [comment]
@mike0042 rebase done.

**Comment by npadole20** [comment]
[fixed_pbs_ralter.txt](https://github.com/PBSPro/pbspro/files/1718877/fixed_pbs_ralter.txt)
Attaching testing log for the fix.

**Pull request merged**
