### PR TITLE
PP-399: PBS Pro spec file should allow sendmail or postfix to satisfy …

### PR DESCRIPTION
**Pull request by mike0042**
#### Issue-ID

* **[PP-399](https://pbspro.atlassian.net/browse/PP-399)**

#### Problem description
* Admin should be able to install PBS Pro server with either sendmail or postfix installed.

#### Cause / Analysis
* Previously, sendmail was listed as a requirement in the spec file and PBS Pro server would not install if only postfix was installed.

#### Solution description
* Change requirement such that it relies on virtual target smtp_daemon (for SUSE) or smtpdaemon (for others). Simply installing the PBS Pro server is the test for this change.

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [X] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [X] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

…requirements

### CODE REVIEW

**Comment by agrawalravi90** [comment]
I was waiting for somebody with more knowledge about these packages to comment first. Just making sure I understand this change correctly: does smtp_daemon/smtpdaemon get resolved to either postfix or sendmail, depending on whichever is installed on the system?

**Comment by mike0042** [comment]
Correct, smtpdaemon/smtp_daemon are defined as "virtual packages" by both sendmail and postfix. Either one will satisfy the requirement. You can find more information on virtual packages here: http://www.rpm.org/max-rpm/s1-rpm-depend-manual-dependencies.html#S3-RPM-DEPEND-VIRTUAL-PACKAGES

**Comment by agrawalravi90** [comment]
Awesome, thanks for the clarifications, I sign-off.

**Comment by agrawalravi90** [comment]
I'll merge it in after a second review

**Comment by bremanandjk** [comment]
I sign-off on these changes.

**Pull request merged**
