### PR TITLE
PP-453: add header to PTL test file added through PP-367

### PR DESCRIPTION
**Pull request by prakashcv13**
#### Issue-ID

* **[PP-453](https://pbspro.atlassian.net/browse/PP-453)**

#### Problem description
* Missed out on adding the header while fixing PP-367

#### Cause / Analysis
* Adding header is mandatory.

#### Solution description
* Added the header

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by prakashcv13** [comment]
No PTL test case or documentation is required for this change.

**Comment by arungrover** [comment]
Prakash, your change looks good.
Please squash the commits into one.

**Comment by agrawalravi90** [comment]
@prakashcv13 There are whitespace differences between this header and that of the existing ptl tests. Could you please make it consistent? Look at __init__.py for reference (it passes the pep8 check). Thanks!

**Comment by prakashcv13** [comment]
@agrawalravi90, done!

**Comment by agrawalravi90** [comment]
Thanks, I sign-off, please squash so we can merge it in.

**Comment by prakashcv13** [comment]
@agrawalravi90, squashed!
Once the CI passes, go ahead and merge this one.

**Pull request merged**
