### PR TITLE
PP-580: qorder between jobs submitted to different queue in the same second does not work

### PR DESCRIPTION
**Pull request by arungrover**
#### Issue-ID

* **[PP-580](https://pbspro.atlassian.net/browse/PP-580)**

#### Problem description
On issuing qorder on 2 jobs submitted to different queue in the same second, their order does not change at all.

#### Cause / Analysis
This particular issue comes only when we are doing qorder between two jobs submitted to 2 different queue and in the same second. When the jobs are from different queue we de-queue each one of them, switch their queue and en-queue them back again. During en-queue we place the job according to their qrank in all-jobs list. In this case both the jobs have the same qrank value so their position never changes and that is why qorder fails.

#### Solution description
Changing qrank to store epoch in milliseconds rather than seconds. This will reduce the likelihood of having two jobs with the same qrank value. But, theoretically it is possible to have two jobs having the same qrank when pbs_server starts accepting more than 60000 jobs/minute.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by vinodchitrali** [comment]
Sign off

**Comment by rampranesh** [comment]
Changes looks good to me!

**Comment by arungrover** [comment]
rebased it with master

**Comment by bhroam** [comment]
Works for me.  I sign off.

**Comment by bhroam** [comment]
Merged.

**Pull request merged**
