### PR TITLE
PP-721, PP-722, PP-736, PP-737, PP-738: Several PTL framework bug fixes

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Issue-ID

* **[PP-721](https://pbspro.atlassian.net/browse/PP-721)**
* **[PP-722](https://pbspro.atlassian.net/browse/PP-722)**
* **[PP-736](https://pbspro.atlassian.net/browse/PP-736)**
* **[PP-737](https://pbspro.atlassian.net/browse/PP-737)**
* **[PP-738](https://pbspro.atlassian.net/browse/PP-738)**

#### Problem description
* Several PTL framework bug fixes as below:
* **PP-721**: -u argument is missing while calling pbs_diag in saving post analysis data
* **PP-722**: While saving post analysis data PTL saves given max threshold + 1 for max post data
* **PP-736**: Make log_match method to fail when no match found for given log message so that user does not have to assert in test case
* **PP-737**: expect failure should be reported as failure rather than error
* **PP-738**: test failure in setUpClass leads to wrong statistics count in summary 

#### Cause / Analysis
* **PP-721**: -u argument is required to collect pbs_dtj information if you have jobs in systems, without -u argument pbs_diag will skip collecting pbs_dtj information for specified jobs
* **PP-722**: due to wrong if condition PTL saves given max threshold + 1 for max post data
* **PP-736**: Currently log_match returns None when no match found for given log message and so test writer has to capture that None and based on that return value test writer has to write assert call
* **PP-737**: currently expect failure is reported as error where it is not because expect fail is something like tests desired condition doesn't meet which is an test failure not an error
* **PP-738**: In python unittest framework whenever test fails in setUpClass, framework doesn't increase testsRun count which leads to negative number in summary

#### Solution description
* **PP-721**: added -u <current user who invoked pbs_benchpress> while calling pbs_diag in post data saving
* **PP-722**: corrected if condition
* **PP-736**: modified log_match method to throw assert failure whenever no match found for given log message
* **PP-737**: modified PtlExpectError to new introduced PtlfailureException (which is nothing but PTL modified version of assert failure aka failure in terms of testing framework) from PtlException (which is nothing but PTL modified version of Exception aka error in terms of testing framework)
* **PP-738**: corrected calculation of statistics count in summary by collecting success info along with error, failure, skipped and timedout infos

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [ ] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by hirenvadalia** [comment]
Hi,
In the interest of time and to cut off review and merging process I am raising one PR with 5 PTL bug fixes...
Also I have intentionally kept 6 commits, one commit for each bug fixes (aka ticket) + one pep8 fixes, so that it will help reviewers to review each fix separately and will squash all of them into one commit before merge.

**Comment by hirenvadalia** [comment]
Also since this is just PTL framework bug fixes not new test cases require...
Also once travis completes I will upload its logs to all JIRA ticket...

**Comment by kjakkali** [comment]
@hirenvadalia : following test cases have assertFalse() , not checking return value. I feel these tests also need to be updated.
 - cgroups_tests.py
 - pbs_only_small_files_over_tpp.py
 - pbs_server_periodic_hook.py
 - pbs_accumulate_resc_used.py
 - pbs_admin_suspend.py

**Comment by hirenvadalia** [comment]
@kjakkali Thanks for review...

* cgroups_tests.py - There is an already ticket for making change in this file so I didn't change anything in this file... see [PP-414](https://pbspro.atlassian.net/browse/PP-414)
* pbs_only_small_files_over_tpp.py - Updated.
* pbs_server_periodic_hook.py - I don't think this file need any further update
* pbs_accumulate_resc_used.py - Updated.
* pbs_admin_suspend.py - I don't think this file need any further update

**Comment by hirenvadalia** [comment]
updated branch with upstream...

**Comment by saritakh** [comment]
PP-721 & PP-722 changes look good to me.

**Comment by arungrover** [comment]
@hirenvadalia I think it would be easy to review these bug fixes if they were part of different pull requests. They way it is structured right now, there are 9 commits for 5 tickets and it becomes difficult to link them together and review. With more changes number of commits will grow.

I see that you have already received sign-off on a couple of them. I'd request you to submit them in different pull requests and reviewers can sign-off again. It will also easier to track and test each change independently.

**Comment by hirenvadalia** [comment]
@arungrover Thanks Arun. I can understand your point, having separate PR for distinct issues is absolutely good idea. I did this because there were very very small changes (like one character or one word change) to fix issue and I was already raising PR for another fix with more changes so I thought lets save some time for everyone by clubbing them together.
Will separate out them soon...

**Pull request closed without merging**
