### PR TITLE
PP-844: Fixed test_normal_user_unable_to_see_res_released ptl test

### PR DESCRIPTION
**Pull request by arungrover**
#### Issue-ID

* **[PP-844](https://pbspro.atlassian.net/browse/PP-844)**

#### Problem description
The ptl script submitted under [THIS](https://github.com/PBSPro/pbspro/pull/446) pull request was wrongly using return value of self.server.status() method

#### Cause / Analysis
Return value of self.server.status() is an array of dict rather than a dict

#### Solution description
Treat the return value as a list of dict

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by vccardenas** [comment]
I sign off on the updates to the test.

**Comment by arungrover** [comment]
@PBSPro/pbspro-maintainers it is pending a maintainer review. Please have a look

**Comment by bhroam** [comment]
Please rebase for the merge.

**Comment by arungrover** [comment]
Thanks @bhroam, I've rebased it.

**Comment by bhroam** [comment]
I merged in the PR

**Pull request merged**
