### PR TITLE
fix test/fw/setup.py filename

### PR DESCRIPTION
**Pull request by minghui-liu**
#### Issue-ID

* **[PP-939](https://pbspro.atlassian.net/browse/PP-939)**

#### Problem description
* Describe the issue being fixed
PTL install command
```
pip install -r requirements.txt .
``` 
stopped working. Pip complains that it cannot find `setup.py`

#### Cause / Analysis
* Briefly describe root cause/analysis of the problem
'setup.py' was renamed to `setup.py.in`

#### Solution description
* Please describe your changes in detail for reviewers
This PR simply changes it back.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by agrawalravi90** [comment]
To elaborate a bit more, Autotools takes care of creating setup.py from setup.py.in (see configure.ac). So, try running configure once, you'll see the setup.py generated. You can then install PTL.

But we should probably mention in our PTL quick start guide that one needs to run configure before installing PTL.

**Comment by minghui-liu** [comment]
@hirenvadalia @hirenvadalia I see. Thanks for the explaination. Will close this PR and JIRA ticket.
And yes we should modify the quick start guide to avoid future confusions.

**Comment by agrawalravi90** [comment]
Actually I just saw and the quick start guide indeed says the right thing:

2. Installing, Upgrading, and Uninstalling PTL
2.1 Installing PTL

Run the following commands:

**Please follow step 1 to 6 mentioned in https://github.com/PBSPro/pbspro/blob/master/INSTALL to configure PBS/PTL**

 cd pbspro/test/fw

To install package run following:

 pip install -r requirements.txt .

**Comment by minghui-liu** [comment]
@agrawalravi90 I don't know how I missed that. Thank you.

**Pull request closed without merging**
