### PR TITLE
Fix for PP-262: Add pull request template

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Issue
* PP-262

#### Problem
* Add pull request template such that it helps contributors what to mention while creating pull request

#### Cause
* None

#### Solution
* Added pull request template in .github/PULL_REQUEST_TEMPLATE.md

### CODE REVIEW

**Comment by hirenvadalia** [comment]
@mike0042 I have updated template after discussion with @arungrover and @subhasisb, please have a look again.

**Comment by hirenvadalia** [comment]
sorry by mistake I closed pull... reopening it.

**Comment by mike0042** [comment]
@hirenvadalia Looks fine to me.

**Comment by arungrover** [comment]
Looks good Hiren.

**Comment by subhasisb** [comment]
The template looks good Hiren

**Comment by subhasisb** [comment]
However, please sync with branch with base and squash your commits into a single one

**Comment by hirenvadalia** [comment]
@mike0042 @subhasisb @arungrover Thanks for reviewing template.

@subhasisb I have synced branch with base and squashed commits into one, please review them...

**Pull request merged**
