### PR TITLE
Remove capturing rscs_all file from pbs_snapshot

### PR DESCRIPTION
**Pull request by agrawalravi90**
#### Bug/feature Description
* rscs_all file was created using a hard-coded list of builtin resources + custom resources. The hardcoded list was a temporary solution until PBS was enhanced to allow querying all builtin resources. But, it doesn't seem like there's much motivation for capturing builtin resources in snapshots as that list doesn't change a lot. So, it's better to remove capturing rscs_all altogether, custom resources are already captured inside resourcedef file.

#### Affected Platform(s)
* All

#### Solution Description
* Removed any and all referenced to the rscs_all file from pbs_snaputils.py

#### Testing
* Just removing a piece of data that pbs_snapshot used to capture, running the already existing snapshot unit tests should be good enough to test this change.
* [test.log](https://github.com/PBSPro/pbspro/files/1730058/test.log)

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [X] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [X] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by agrawalravi90** [comment]
Thanks Bhroam, requesting one more review please, this is a very small and easy code change, thanks!

**Comment by agrawalravi90** [comment]
:) Thanks Mike, I'll rebase and let you guys know when this is ready for merge

**Comment by mike0042** [comment]
Just merged something Anamika was waiting on. Please rebase once more.

**Comment by agrawalravi90** [comment]
@PBSPro/pbspro-maintainers this is ready for merge, thanks!

**Comment by bhroam** [comment]
I merged in the PR.

**Pull request merged**
