### PR TITLE
PP-250: Hook debug causes file descriptor leak that crashes PBS server

### PR DESCRIPTION
**Pull request by bayucan**
Fix issue where hook debug=True causes file descriptor leak that crashes PBS server
#### Issue-ID

* PP-250

#### Problem description
When there are multiple server hooks (not in mom hooks) responding to the same event (e.g. queuejob), and some hooks have debug=True, this causes server to run out of file resources which result in either a server crash. or qsub fails with "invalid credential" or qsub/qstat hangs with a message in server_logs that goes: "too many open files".

#### Cause / Analysis
In server/hook_func.c: process_hooks(), while processing each hook responding to the same event, server is "forgetting" any previously opened hook debug output file

#### Solution description
* Fclose() hook debug output file pointer of a previous hook that had debug=True, before assigning a new one.
* I now also fclose() the hook debug output file pointer before early exit from the process_hooks() function.

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [X] I have added tests to cover my changes. To create automated tests, see **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**.
- [X] All new and existing automated tests have passed. See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**.
- [X] I have attached automated (PTL)/manual test logs to the associated Jira ticket.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by mike0042** [comment]
Looks good. I sign off.

**Comment by bhroam** [comment]
Other than Mike's comment, I'm fine with the code.  I sign off.

**Comment by bayucan** [comment]
I've ran the autopep8 on the pbs_hook_debug_nocrash.py file, and have pushed the new, squashed commit. Please re-review.

**Comment by bhroam** [comment]
Looks good, I sign off

**Comment by mike0042** [comment]
I sign off. You'll need to update your branch prior to the merge.

**Comment by bayucan** [comment]
I've updated the branch!

**Comment by mike0042** [comment]
I'll merge it once the Travis-CI check passes.

**Pull request merged**
