### PR TITLE
PP-1111 Calling pbs_benchpress with a bad argument runs tests

### PR DESCRIPTION
**Pull request by vstumpf**
#### Issue-ID

* **[PP-1111](https://pbspro.atlassian.net/browse/PP-1111)**

#### Problem description
* Calling pbs_benchpress with a bad argument runs tests

#### Cause / Analysis
* pbs_benchpress does not check the list of arguments

#### Solution description
* if there are arguments in `args`, then print usage and exit.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by agrawalravi90** [comment]
Looks fine to me as well, please rebase and squash

**Comment by mike0042** [comment]
@vstumpf please rebase your branch so we can get this merged.

**Comment by vstumpf** [comment]
I've rebased @mike0042

**Comment by vstumpf** [comment]
Thanks @mike0042!

**Pull request merged**
