### PR TITLE
PP-211: Scheduler dumps core for suspended jobs..

### PR DESCRIPTION
**Pull request by agrawalravi90**
#### Issue-ID

* **[PP-211](https://pbspro.atlassian.net/browse/PP-211)**

#### Problem description
* Scheduler dumps core for suspended job, when sched cycle is kicked, if requested vnode by job has been deleted

#### Cause / Analysis
* Inside 'collect_jobs_on_nodes()', line 1463, we were dereferencing 'ninfo_arr' for suspended jobs, which would be NULL if the node on which a suspended job was running got deleted.

#### Solution description
* Added a check for NULL, now we will only dereference 'ninfo_arr' if it is not NULL.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
While what you did in the scheduler will fix the bug, I don't believe it is the root cause of the issue.  If you try and delete a node with a running job on it, you get a message about not being able to delete a busy node.  If you try and delete a node that has a suspended job on it, it works.  A suspended job is just like a running job, except the processes are sleeping.  You shouldn't be able to delete a node with a suspended job on it.

**Comment by agrawalravi90** [comment]
Ah, I didn't know that was the correct behavior, it does make sense, I'll make it so that one can't delete a node with suspended jobs on it, thanks!

**Comment by agrawalravi90** [comment]
I'm not getting bandwidth to work on this, this ticket is up for grabs for anybody else who'd like to work on this.

**Comment by bhroam** [comment]
@agrawalravi90 instead of closing this PR, how about we merge it and file a separate bug for the server issue?  This will stop the scheduler from crashing while we wait for the time to fix the server issue.

**Comment by agrawalravi90** [comment]
Alright, that sounds good to me, I've filed the bug for fixing the behavior here: https://pbspro.atlassian.net/browse/PP-744

Please let me know if the changes for this PR look good for fixing the crash itself. Thanks!

**Comment by agrawalravi90** [comment]
Thanks @bhroam I just rebased. Requesting @PBSPro/pbspro-maintainers to merge this in.

**Pull request merged**
