### PR TITLE
TestNodePartition fails due to incorrect node id

### PR DESCRIPTION
**Pull request by latha-subramanian**
#### Bug/feature Description
TestNodePartition fails due to incorrect node id used in the tests.

#### Affected Platform(s)
* All 

#### Cause / Analysis / Design
FQDN is used as node id in manager calls to set partition attribute. But node ids are short names.

#### Solution Description
Use short names rather than FQDN so the node ids match

#### Testing logs/output
[beforefix.txt](https://github.com/PBSPro/pbspro/files/2590451/beforefix.txt)
[afterfix.txt](https://github.com/PBSPro/pbspro/files/2590455/afterfix.txt)

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by latha-subramanian** [comment]
Thanks @vstumpf, @bhroam  .
I have squashed and rebased for merge.  Please take it forward.

**Comment by bhroam** [comment]
Looks like you are out of date.  Please rebase again.

**Comment by latha-subramanian** [comment]
@bhroam , I have rebased again. Please take it forward

**Comment by latha-subramanian** [comment]
@bhroam, All checks have passed after rebase. Please take it forward

**Comment by latha-subramanian** [comment]
Looks like something got merged again ! Rebasing again for merge

**Comment by bhroam** [comment]
I merged in the PR.

**Pull request merged**
