### PR TITLE
PP-583: Fixing Windows build issue

### PR DESCRIPTION
**Pull request by vinodchitrali**
#### Issue-ID

* **[PP-583](https://pbspro.atlassian.net/browse/PP-583)**

#### Problem description
* Windows build is broken

#### Cause / Analysis
* Libpbs.vcproj is not updated for ifl_impl.c

#### Solution description
* add ifl_impl.c to Libpbs.vcproj

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by suresh-thelkar** [comment]
Code change looks good to me.

**Comment by rampranesh** [comment]
Changes look good to me!

**Comment by arungrover** [comment]
@vinodchitrali whole file shows up as modified in the diff. By any chance have you changed the line endings?

**Comment by arungrover** [comment]
Closing the pull request... Same issue has been addressed by another developer ( @rampranesh )

**Pull request closed without merging**
