### PR TITLE
Normalize node table code

### PR DESCRIPTION
**Pull request by nithinj**
This is a code refactoring and clean-up effort for better maintainability of code and preparing the codebase better suitable for future scalability enhancements. Node object was handled completely different in comparison to other objects for various reasons. This is an effort to generalize it.

Targets on:
* Remove special save functions for node.
Special save functions for individual attributes are not required as we are encoding only the modified flags while writing into the database. Encoded attributes will get updated in the table which is handled by Postgres internally. 

* Remove associated flags.
* Remove special cases within svr_to_db_node and invoke db_to_attr_db()
* Replace node_recov_db_raw() with node_recov_db().
raw load won't trigger action routines. which was required as some action routines such as indirect resource will refer to other nodes that may not have loaded yet. So action functions are called only after loading all nodes. This behaviour is changed to load the node when it is being referred.

* Additional node saves?
Node saves are not introduced in the job run path to avoid any performance penalty. It will only save only the updated attribute reducing the I/O. Right now static area will get saved anyway. Which will be solved using checksums in the future.

notes for maintainers:
It can be targeted for the next major release to buy more time for regressions.

### CODE REVIEW

**Comment by agrawalravi90** [comment]
@nithinj I don't really see any value keeping this PR open if it won't get reviewed until we fork off 2020.1. What do you think?

**Comment by nithinj** [comment]
@agrawalravi90 
I can close the PR if it cannot be reviewed. But I was hoping to complete the review by the time we fork a new release branch. Thanks!

**Comment by agrawalravi90** [comment]
Oh, ok, I thought that we were going to go the integration branch route. Aren't you planning to put this in the integration branch as well?

**Comment by nithinj** [comment]
I wasnt planning to. But I guess this changes will be helpful for the integration branch if we push the release further. Closing this now.

**Pull request closed without merging**
