### PR TITLE
PP-863: scheduler won't run jobs in the same equiv class if there is …

### PR DESCRIPTION
**Pull request by bhroam**
…a suspended job in the list, but isn't the first job

#### Issue-ID

* **[PP-863](https://pbspro.atlassian.net/browse/PP-863)**

#### Problem description
* Suspended jobs need to be resumed on the same nodes they were run on.  Suspended jobs are being added into the same equivalence class they were in when they were queued.  Suspended jobs are considered to run first.  If the nodes that the suspended was run on are not available, it will mark the entire class as can not run.  The queued jobs in that class can run anywhere, but now they're in a class that can't run.

#### Cause / Analysis
* This is the second half of this bug fix.  The two halves have to do the query order of the jobs.  Equivalence classes are created in job query order.  The first job in the class creates it and other jobs are added to it.  The original fix only caught the problem if the suspended job came first.  This fix handles the case if the suspended job is a subsequent job.

#### Solution description
* suspended jobs have a special select spec generated for them.  It's based on the original select spec and the vnodes the job is suspended on.  The original fix had logic to use the correct select spec (the special or the original) when classes were being created.  This logic needs to be used in both the code which creates a set and when it finds a set.

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [X] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [X] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [X] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
Thank you for your comment @altair4.  I reevaluated the code and looked into the compare functions themselves.  They handle the case of NULL perfectly well.  In fact, they handle it better than I was.  I removed the checks for NULL on the three compare calls you were commenting on.  I compiled with -Wall and noticed a bunch of warnings.  The rest of the code you see changed is fixing warnings.  They are mostly unused variables.  One variable was being set but not used.  That sort of thing.

**Comment by arungrover** [comment]
@bhroam your change looks good to me.

Please rebase and squash your changes

**Comment by bhroam** [comment]
squashed and rebased

**Comment by arungrover** [comment]
Merged

**Pull request merged**
