### PR TITLE
Fix rpmlint warning: manpage-not-compressed

### PR DESCRIPTION
**Pull request by minghui-liu**
#### Bug/feature Description
* rpmlint reported warning: manpage-not-compressed

#### Affected Platform(s)
* RHEL, Fedora, CentOS, openSUSE

#### Cause / Analysis / Design
* rpm does not automatically compress man pages if a custom install prefix is used.

#### Solution Description
* Manually compress man pages in the %make_install section of the spec file.

#### Testing logs/output
* [compress_man_page_manual_test.txt](https://github.com/PBSPro/pbspro/files/2928451/compress_man_page_manual_test.txt)

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [x] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by minghui-liu** [comment]
pbspro.spec file will be generated from its spec.in file during configure right? I do not know why we keep the spec file in our repo.

**Comment by mike0042** [comment]
@minghui-liu - You will need to run autogen.sh and it will generate the new pbspro.spec from pbspro.spec.in

**Comment by vstumpf** [comment]
The windows build needs it to pull the version number out:
https://github.com/PBSPro/pbspro/blob/e605ee30cf94cedfd37a9247cfc7df3f78c0f78d/win_configure/msi/wix/create_msi.bat#L67-L70

**Comment by mike0042** [comment]
@vstumpf is correct. I updated the version to 19.0.0 some time ago in pbspro.spec. For non-Windows builds the version number may be overridden by defining pbs_version during rpmbuild.

**Comment by hirenvadalia** [comment]
> pbspro.spec file will be generated from its spec.in file during configure right? I do not know why we keep the spec file in our repo.

@minghui-liu Just answering to your question: Mainly for 2 reason we have kept pbspro.spec file in repo,
1) as @vstumpf pointed Windows build scripts uses pbspro.spec to get PBS version
2) In Travis we use `yum-builddep -y ./pbspro.spec` to install build dependency before we run autogen.sh or configure (https://github.com/PBSPro/pbspro/blob/master/.travis/centos_7.sh#L6)

HTH!

**Pull request merged**
