### PR TITLE
Removing checksign from Travis

### PR DESCRIPTION
**Pull request by agrawalravi90**
#### Bug/feature Description
* Github now has the ability to block a PR if it contains any commits which are not signed, so we should remove the check in Travis which does the same.

#### Affected Platform(s)
* N/A

#### Cause / Analysis / Design
* See Description

#### Solution Description
* Removed checksign from Travis and deleted the script

#### Testing
* This PR just removes a redundant check from Travis, so testing would simply be Travis passing.

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by agrawalravi90** [comment]
@ashwathraop , @subhasisb already turned on Githib's check for signed commits. I tried the feature out in one of my dummy projects, take a look at this PR: https://github.com/agrawalravi90/project/pull/4, it has 2 commits, one signed and one not signed, and you'll see that Github has blocked that PR from getting merged. So, it seems like our own checksign check is not needed anymore as Github's feature seems to work sufficiently well.

**Comment by mike0042** [comment]
Please rebase @agrawalravi90

**Comment by agrawalravi90** [comment]
Thanks Mike, I just rebased, I'll notify again once the CI passes.

**Comment by agrawalravi90** [comment]
@PBSPro/pbspro-maintainers , this is ready for merge, thanks!

**Pull request merged**
