### PR TITLE
Restore ability to build with -DDEBUG flag

### PR DESCRIPTION
**Pull request by brewlius-cesar**
#### Issue-ID

* **[PP-1101](https://pbspro.atlassian.net/browse/PP-1101)**

#### Problem description
* Previously unable to build with CFLAGS=-DDEBUG to turn on the debug printing

#### Cause / Analysis
* Seems just some simple code fixes, missed because this code vanishes unless DEBUG defined

#### Solution description
A couple of `DBPRT` statememts contained `id` with the expectation
that `DOID()` macro would be defined earlier in the function. For these
statements `id` is replaced with `__func__` since that seems to be
what is used at other places in the file.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by brewlius-cesar** [comment]
Rebased.

I was thinking of adding a debug run to the CI matrix but wasn't sure it would be desired.

**Comment by subhasisb** [comment]
@brewlius-cesar what you said makes a lot of sense. Please feel free to add a debug build to the CI.

**Comment by bhroam** [comment]
@brewlius-cesar usually evidence of testing needs to be attached to the PP ticket.  In this case I think the best evidence we can have is that a -DDEBUG build compiles.  Can you compile with -DDEBUG and attach that to the PP ticket?

**Comment by brewlius-cesar** [comment]
Sorry for the delay, I attached a build log to the ticket.

I looked into adding DEBUG builds to the CI matrix, but one problem I came across is that t pbs_server does not fork to the background when DEBUG is defined.  Seems to  be around https://github.com/PBSPro/pbspro/blob/c8dcd17683970d2d29f4131dad1fb7f5d18fc369/src/server/pbsd_main.c#L398 and https://github.com/PBSPro/pbspro/blob/c8dcd17683970d2d29f4131dad1fb7f5d18fc369/src/server/pbsd_main.c#L1761.

Since there is already a runtime option for keeping the server in the foreground, why is it explicitly disabled when DEBUG is defined?

**Comment by subhasisb** [comment]
Hi @brewlius-cesar When DEBUG is defined, the code spits out a lot of debug information on stdout. If we allow it to fork and go to the background, then this information is lost. And such a build with -DDEBUG was mostly intended for manual use by the developers, and nobody thought about CI/automation at that point.

I see the usefulness of removing this restriction and allowing it to go to background by default. In addition we can redirect stdout to some output file, so that it is also not lost (when -N is not specified on the command line). If you like this idea, would you like to work on this code change?

**Comment by subhasisb** [comment]
@brewlius-cesar for this PR, can you please update your commit? It is out of date with the base.

**Comment by brewlius-cesar** [comment]
Rebased again.

As for the forking on debug builds: its definitely not a bug and it is not really a feature I would be interested in, so I am going to pass on working on that for now.

Let me know if anything more is needed for this PR.

**Comment by subhasisb** [comment]
@brewlius-cesar thanks - i will merge it asap.

**Comment by subhasisb** [comment]
Merged!

**Comment by mike0042** [comment]
@subhasisb it doesn't appear to be merged. It still shows up as open. Not sure anything is going to build properly until the Travis components get sorted out.

**Comment by subhasisb** [comment]
@mike0042 sorry i think earlier i hit merge but failed to notice that the CI hook rejected it due to Travis failure. Today, of course the code needed rebasing, so I did via another PR. Thanks @brewlius-cesar

**Pull request merged**
