### PR TITLE
PP-1092: TestJobRouting has typo for setUp function

### PR DESCRIPTION
**Pull request by prakashcv13**
#### Issue-ID

* **[PP-1092](https://pbspro.atlassian.net/browse/PP-1092)**

#### Problem description
* test_t2 of TestJobRouting is failing.

#### Cause / Analysis
* The test case depends on the "setup" to have ncpus=3, however, setUp is mistyped as setup, so the "setup" does not happen.

#### Solution description
* Corrected the typo.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [x] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by Klovely** [comment]
Changes look good to me .

**Comment by prakashcv13** [comment]
@Klovely - if the changes look good to you, please approve the changes.

**Comment by prakashcv13** [comment]
@PBSPro/pbspro-maintainers - this is a trivial change - request someone to review and merge.

**Comment by arungrover** [comment]
Please update the branch

**Comment by prakashcv13** [comment]
@arungrover - just did - thank you!

**Comment by arungrover** [comment]
I think something else made it in before I can get on to this ticket. Can you please rebase it again.

**Comment by prakashcv13** [comment]
@arungrover - did it again.

**Pull request merged**
