### PR TITLE
PP-943: Ignore files generated by PTLTestLab

### PR DESCRIPTION
**Pull request by minghui-liu**
#### Issue-ID

* **[PP-943](https://pbspro.atlassian.net/browse/PP-943)**

#### Problem description
In [PP-785](https://pbspro.atlassian.net/browse/PP-785) `test/fw/setup.py` and `test/fw/ptl/__init__.py` were changed to be generated by autotools. As a developer I don't want them to be tracked by git. 

#### Cause / Analysis
`test/fw/setup.py` and `test/fw/ptl/__init__.py` were not in `.gitignore` file.

#### Solution description
Add `test/fw/setup.py` and `test/fw/ptl/__init__.py` to `.gitignore`. 

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by prakashcv13** [comment]
@minghui-liu, I am making these changes as part of PR#346.

**Comment by minghui-liu** [comment]
@prakashcv13 Thank you. Would you please provide a link to it?

**Comment by hirenvadalia** [comment]
Here is the link for PR which @prakashcv13 is referring #346

**Comment by minghui-liu** [comment]
Thank you @hirenvadalia . Closing this PR.

**Pull request closed without merging**
