### PR TITLE
PP-776: mom's chk_file_sec messages missing when syslog is being used

### PR DESCRIPTION
**Pull request by nithinj**
#### Issue-ID

* **[PP-776](https://pbspro.atlassian.net/browse/PP-776)**

#### Problem description
* mom's chk_file_sec messages missing when syslog is being used

#### Cause / Analysis
* The function returns before printing to stderr when syslog is configured.

#### Solution description
* The stderr is printed before returning from function log_err().

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by nithinj** [comment]
I've re-based the branch. Please take it forward.

**Comment by nithinj** [comment]
Hi @bhroam and @bremanandjk 
I've addressed this issue in a better way with commit-2. Attached the recent logs with the ticket. I request you to review it once more. 
Thanks!

**Comment by bremanandjk** [comment]
I am still fine with my Sign-off on this new commit. New solution looks good to me.

**Comment by bhroam** [comment]
I like the new solution.  It reuses code.  Please squash and rebase for the merge.

**Comment by nithinj** [comment]
Squashed and re-based. Please take it forward.

**Pull request merged**
