### PR TITLE
PP-322: Merge NASA Mods since 13.0 into mainline

### PR DESCRIPTION
**Pull request by bhroam**
#### Issue-ID
* PP-322

#### Problem description
* Merge latest set of NASA mods into PBS source

#### Cause / Analysis
* NASA has continued to make mods since v13. 

#### Solution description
* Merge in their changes into the source.  

How to do this review: Their half of the ifdef is their responsibility.  Please review the PBS half and make sure it looks good.  Also, half of the changes are in a file called site_code.c.  Please ignore this file because the entire file is ifdef'd out.

This request does not require a PTL test because our code has not changed.  Their code is ifdef'd out.

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added tests to cover my changes. To create automated tests, see **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**.
- [x] All new and existing automated tests have passed. See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**.
- [x] I have attached automated (PTL)/manual test logs to the associated Jira ticket.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bayucan** [comment]
I've reviewed all the files. The only thing I found is:

src/scheduler/site_data.h:
Missing the "#ifdef NAS" directive.

The rest of the files are good.

src/resmom/start_exec.c: ok
src/cmds/scripts/install_db: ok
src/cmds/scripts/pbs_dataservice: ok
src/include/cmds.h:ok
src/lib/Libtpp/tpp_client.c: ok
src/lib/Libtpp/tpp_transport.c: ok
src/resmom/mom_main.c:ok
src/resmom/stage_func.c:ok
src/scheduler/check.c: ok
src/scheduler/data_types.h:ok
src/scheduler/fifo.c:ok
src/scheduler/fifo.h:ok
src/scheduler/job_info.c:ok
src/scheduler/parse.c:ok
src/scheduler/sort.c:ok
src/server/accounting.c:ok
src/server/node_func.c:ok
src/server/req_manager.c:ok
src/server/req_runjob.c:ok
src/server/svr_func.c:ok
src/scheduler/site_code.c:ok
src/scheduler/site_code.h:ok

**Comment by bayucan** [comment]
I checked the reviewed site_data.h file and it looks good.
I sign off on your NASA mods.

**Comment by mike0042** [comment]
Looks good Bhroam. I sign off.

**Comment by subhasisb** [comment]
@bhroam you may want to attach the travis run logs as evidence of testing for this case. Please add that log to the Jira ticket

**Comment by bhroam** [comment]
Good idea, Subhasis.  I attached the OpenSuSE travis log to the ticket.

**Pull request merged**
