### PR TITLE
Add more detailed information for cgroups in write_value exceptions

### PR DESCRIPTION
**Pull request by vstumpf**
#### Bug/feature Description
The cgroups hook would not give much info if writing the value into the cgroup fails.

#### Affected Platform(s)
Linux

#### Cause / Analysis / Design
The cgroups hook would give no context as to what failed in `write_value`. 

#### Solution Description
Add the value and file that encountered a problem to the exception message.

#### Testing logs/output
None

#### Checklist:

- [ ] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [ ] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [ ] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
   - [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
   - [ ] I have added  **manual test(s) to this pull request and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to this pull request** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by mike0042** [comment]
You may want to re-sign your commit @vstumpf. Looks like some of the CI tests go wedged.

**Comment by vstumpf** [comment]
I think travis is using the github api to tell it's a draft PR, and to not build it. I was waiting until I could figure out a way to test it, but we don't have to test for log messages right? Is this PR complete enough?

**Comment by mike0042** [comment]
I already checked the tests to ensure they weren't looking for any of the messages you changed, and they were not. No new tests required (IMHO) since you're not changing functionality.

**Comment by vstumpf** [comment]
Awesome, I'll kick off the builds again.

**Comment by mike0042** [comment]
@vstumpf you may want to request another reviewer.

**Pull request merged**
