### PR TITLE
PP-407: Replace bash with sh in .travis.yml file (2nd workaround)

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Issue-ID

* **[PP-407](https://pbspro.atlassian.net/browse/PP-407)**

#### Problem description
* As per issue in docker engine (docker/compose#3379) command (in our case cp command) fails with exit code 129.

#### Cause / Analysis
* docker/compose#3379

#### Solution description
* This is 2nd workaround for docker engine issue (docker/compose#3379). In this workaround we are downgrading Docker to 1.9.1 as suggested (by support@travis-ci.com) here https://github.com/travis-ci/travis-ci/issues/6461#issuecomment-239577306

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by kjakkali** [comment]
looks good. I sign off.

**Comment by subhasisb** [comment]
Code looks good. I sign off.

**Comment by subhasisb** [comment]
@hirenvadalia can you kindly also skip the qstat performance test for the normal Travis runs. It seems to be taking too long to finish these days. Lets only run the ones which has the smoketest tag.

**Comment by hirenvadalia** [comment]
@subhasisb I have updated Travis file to run only test which has smoke tag. Please have a look again.
Currently it will run 0 test cases as none of the test cases is marked as "smoke" but once #131 gets merged we will have ~45 test cases under smoke tags.

**Comment by subhasisb** [comment]
All looks good. Merging

**Pull request merged**
