### PR TITLE
PP-984: cput and mem limits kill job even if the value is equal to th…

### PR DESCRIPTION
**Pull request by vchlum**
…e limit

#### Issue-ID

* **[PP-984](https://pbspro.atlassian.net/browse/PP-984)**

#### Problem description
* cput and mem limits kill job even if the value is equal to the limit

#### Cause / Analysis
* The present comparision is "limit <= total_mem" (resp."limit <= total_cpu") and the job is killed once this condition is met, but the job should be killed once the limit is exceeded.

#### Solution description
* replace "<=" with "<"

#### Checklist:

- [X] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [X] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [X] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [X] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [X] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by bhroam** [comment]
Looks good to me.  I sign off.

**Comment by vchlum** [comment]
This PR has two signs-off. I have rebased, and it is ready for merge.

**Comment by mike0042** [comment]
Hello @vchlum, please rebase again.
I'd ask @agrawalravi90 since he is closer to your timezone.

**Comment by vchlum** [comment]
@agrawalravi90 I have rebased again. Please, take it forward.

**Comment by agrawalravi90** [comment]
Looks good to me, merged it in.

**Pull request merged**
