### PR TITLE
PP-593: Remove spurious whitespace causing autotools warning message

### PR DESCRIPTION
**Pull request by billnitzberg**
#### Issue-ID

* **[PP-593](https://pbspro.atlassian.net/browse/PP-593)**

#### Problem description
* Fix autotools build warning: extra whitespace after backslash in src/resmom/Makefile.am

#### Cause / Analysis
* Extra whitespace (after a backslash) caused a warning from auto tools (running initial ./autogen.sh).

#### Solution description
* Removed extra whitespace

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [x] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by billnitzberg** [comment]
Hey @bhroam -- I fixed the one-character warning I mentioned to you already.  Could you do one of the code reviews for me?  Thx.

**Comment by bhroam** [comment]
Looks good to me.  I sign off.

**Comment by subhasisb** [comment]
@billnitzberg could you please prepend the commit message and the PULL request title with the Jira id.
Like: "PP-593: Remove spurious whitespace causing autotools warning message".
That way, its easier for everybody to find the associated jira id's from the commits list (even outside of github)

**Comment by billnitzberg** [comment]
@subhasisb: done; thx.

**Comment by subhasisb** [comment]
@billnitzberg you have change the PR title but not the commit message itself - that one is more important outside of github.

**Comment by billnitzberg** [comment]
OK, might be done correctly this time... :-)  Thx.

**Comment by subhasisb** [comment]
Yep, that looks perfect. Now waiting for CI to finish and will merge right after.

**Pull request merged**
