### PR TITLE
PP-664: Travis builds failing on centos

### PR DESCRIPTION
**Pull request by hirenvadalia**
#### Issue-ID

* **[PP-664](https://pbspro.atlassian.net/browse/PP-664)**

#### Problem description
* Travis build fails on centos

#### Cause / Analysis
* Some of directory on vault.centos.org got changed but yum inside centos docker container still looks into those directory for packages

#### Solution description
* For base yum repo use mirrorlist and for source yum repo use old working version

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **PTL test(s) to my commit**. (See **[using PTL for testing](https://pbspro.atlassian.net/wiki/display/DG/Using+PTL+for+Testing)**) *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why PTL is not appropriate** for this case.
- [x] All new and existing automated tests have passed. (See **[running automated PTL tests](https://pbspro.atlassian.net/wiki/display/DG/PTL+Quick+Start+Guide)**).
- [x] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by hirenvadalia** [comment]
No PTL test or Document require for this as this is just a fix for travis not a product.

**Comment by hirenvadalia** [comment]
Just FYI to all/reviewers: This is just a temporary fix to unblock our pending PRs till we get fix on vault.centos.org and I will create ticket to revert this changes once PR get merged.

**Comment by subhasisb** [comment]
This is a temporary change to allow Travis builds to pass given the changes in the Centos repos. We will revert back as soon as the original problem fixed.

**Comment by hirenvadalia** [comment]
Here is ticket to revert changes done as part this PR: [PP-666](https://pbspro.atlassian.net/browse/PP-666)

**Pull request merged**
